using System;
using System.Collections.Generic;
using System.Globalization;
using Windows.Storage;

namespace Notelockv3.Services;

public class LanguageInfo
{
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string NativeName { get; set; } = string.Empty;
    public bool IsRightToLeft { get; set; }
}

public class LocalizationService
{
    private static readonly Lazy<LocalizationService> _instance = new Lazy<LocalizationService>(() => new LocalizationService());
    public static LocalizationService Instance => _instance.Value;

    public const string AUTO_CODE = "auto";
    private const string PREF_KEY = "SelectedLanguage";

    public event EventHandler? LanguageChanged;

    public string SelectedLanguageCode { get; private set; } = AUTO_CODE;
    public string ResolvedLanguageCode { get; private set; } = "en";

    public bool IsRightToLeft => GetLanguageInfo(ResolvedLanguageCode)?.IsRightToLeft ?? false;

    public static readonly List<LanguageInfo> SupportedLanguages = new()
    {
        new LanguageInfo { Code = "auto", Name = "System Auto", NativeName = "Auto (System Language)", IsRightToLeft = false },
        new LanguageInfo { Code = "en", Name = "English", NativeName = "English", IsRightToLeft = false },
        new LanguageInfo { Code = "zh-CN", Name = "Mandarin Chinese", NativeName = "简体中文", IsRightToLeft = false },
        new LanguageInfo { Code = "hi", Name = "Hindi", NativeName = "हिन्दी", IsRightToLeft = false },
        new LanguageInfo { Code = "es", Name = "Spanish", NativeName = "Español", IsRightToLeft = false },
        new LanguageInfo { Code = "fr", Name = "French", NativeName = "Français", IsRightToLeft = false },
        new LanguageInfo { Code = "ar", Name = "Modern Standard Arabic", NativeName = "العربية", IsRightToLeft = true },
        new LanguageInfo { Code = "bn", Name = "Bengali", NativeName = "বাংলা", IsRightToLeft = false },
        new LanguageInfo { Code = "pt", Name = "Portuguese", NativeName = "Português", IsRightToLeft = false },
        new LanguageInfo { Code = "ru", Name = "Russian", NativeName = "Русский", IsRightToLeft = false },
        new LanguageInfo { Code = "ur", Name = "Urdu", NativeName = "اردو", IsRightToLeft = true },
        new LanguageInfo { Code = "id", Name = "Indonesian", NativeName = "Bahasa Indonesia", IsRightToLeft = false },
        new LanguageInfo { Code = "de", Name = "German", NativeName = "Deutsch", IsRightToLeft = false },
        new LanguageInfo { Code = "ja", Name = "Japanese", NativeName = "日本語", IsRightToLeft = false },
        new LanguageInfo { Code = "pcm", Name = "Nigerian Pidgin", NativeName = "Naija", IsRightToLeft = false },
        new LanguageInfo { Code = "arz", Name = "Egyptian Arabic", NativeName = "عربي مصري", IsRightToLeft = true },
        new LanguageInfo { Code = "mr", Name = "Marathi", NativeName = "मराठी", IsRightToLeft = false },
        new LanguageInfo { Code = "te", Name = "Telugu", NativeName = "తెలుగు", IsRightToLeft = false },
        new LanguageInfo { Code = "tr", Name = "Turkish", NativeName = "Türkçe", IsRightToLeft = false },
        new LanguageInfo { Code = "ta", Name = "Tamil", NativeName = "தமிழ்", IsRightToLeft = false },
        new LanguageInfo { Code = "yue", Name = "Cantonese", NativeName = "粵語", IsRightToLeft = false },
        new LanguageInfo { Code = "vi", Name = "Vietnamese", NativeName = "Tiếng Việt", IsRightToLeft = false },
        new LanguageInfo { Code = "wuu", Name = "Wu Chinese", NativeName = "吴语", IsRightToLeft = false },
        new LanguageInfo { Code = "tl", Name = "Tagalog", NativeName = "Filipino", IsRightToLeft = false },
        new LanguageInfo { Code = "ko", Name = "Korean", NativeName = "한국어", IsRightToLeft = false },
        new LanguageInfo { Code = "fa", Name = "Persian (Farsi)", NativeName = "فارسی", IsRightToLeft = true },
        new LanguageInfo { Code = "ha", Name = "Hausa", NativeName = "Harshen Hausa", IsRightToLeft = false },
        new LanguageInfo { Code = "jv", Name = "Javanese", NativeName = "Basa Jawa", IsRightToLeft = false },
        new LanguageInfo { Code = "pa", Name = "Punjabi", NativeName = "ਪੰਜਾਬੀ", IsRightToLeft = false },
        new LanguageInfo { Code = "sw", Name = "Swahili", NativeName = "Kiswahili", IsRightToLeft = false },
        new LanguageInfo { Code = "it", Name = "Italian", NativeName = "Italiano", IsRightToLeft = false },
        new LanguageInfo { Code = "yo", Name = "Yoruba", NativeName = "Èdè Yorùbá", IsRightToLeft = false },
        new LanguageInfo { Code = "gu", Name = "Gujarati", NativeName = "ગુજરાતી", IsRightToLeft = false },
        new LanguageInfo { Code = "th", Name = "Thai", NativeName = "ไทย", IsRightToLeft = false },
        new LanguageInfo { Code = "am", Name = "Amharic", NativeName = "አማርኛ", IsRightToLeft = false },
        new LanguageInfo { Code = "bho", Name = "Bhojpuri", NativeName = "भोजपुरी", IsRightToLeft = false },
        new LanguageInfo { Code = "pl", Name = "Polish", NativeName = "Polski", IsRightToLeft = false },
        new LanguageInfo { Code = "ps", Name = "Pashto", NativeName = "پښتو", IsRightToLeft = true },
        new LanguageInfo { Code = "or", Name = "Odia (Oriya)", NativeName = "ଓଡ଼ିଆ", IsRightToLeft = false },
        new LanguageInfo { Code = "nan", Name = "Min Nan Chinese", NativeName = "閩南語", IsRightToLeft = false },
        new LanguageInfo { Code = "ml", Name = "Malayalam", NativeName = "മലയാളം", IsRightToLeft = false },
        new LanguageInfo { Code = "nl", Name = "Dutch", NativeName = "Nederlands", IsRightToLeft = false }
    };

    private readonly Dictionary<string, Dictionary<string, string>> _translations;

    private LocalizationService()
    {
        _translations = BuildTranslations();
        LoadSavedLanguage();
    }

    private void LoadSavedLanguage()
    {
        try
        {
            if (ApplicationData.Current.LocalSettings.Values.TryGetValue(PREF_KEY, out object? val) && val is string code)
            {
                SelectedLanguageCode = code;
            }
            else
            {
                SelectedLanguageCode = AUTO_CODE;
            }
        }
        catch
        {
            SelectedLanguageCode = AUTO_CODE;
        }

        ResolveLanguage();
    }

    public void SetLanguage(string code)
    {
        SelectedLanguageCode = code;
        try
        {
            ApplicationData.Current.LocalSettings.Values[PREF_KEY] = code;
        }
        catch
        {
        }
        ResolveLanguage();
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    private void ResolveLanguage()
    {
        if (SelectedLanguageCode == AUTO_CODE)
        {
            string sysCulture = CultureInfo.CurrentUICulture.Name;
            string sysTwoLetter = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;

            var match = SupportedLanguages.Find(l =>
                l.Code.Equals(sysCulture, StringComparison.OrdinalIgnoreCase) ||
                l.Code.Equals(sysTwoLetter, StringComparison.OrdinalIgnoreCase) ||
                sysCulture.StartsWith(l.Code, StringComparison.OrdinalIgnoreCase));

            ResolvedLanguageCode = match?.Code ?? "en";
        }
        else
        {
            ResolvedLanguageCode = SelectedLanguageCode;
        }
    }

    public LanguageInfo? GetLanguageInfo(string code)
    {
        return SupportedLanguages.Find(l => l.Code.Equals(code, StringComparison.OrdinalIgnoreCase));
    }

    public string GetString(string key, params object[] args)
    {
        if (_translations.TryGetValue(ResolvedLanguageCode, out var dict) && dict.TryGetValue(key, out string? val))
        {
            return args.Length > 0 ? string.Format(val, args) : val;
        }

        if (_translations.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out string? enVal))
        {
            return args.Length > 0 ? string.Format(enVal, args) : enVal;
        }

        return key;
    }

    private static Dictionary<string, Dictionary<string, string>> BuildTranslations()
    {
        var map = new Dictionary<string, Dictionary<string, string>>();

        void AddLang(string code, string file, string newDoc, string newWin, string open, string save, string saveAs, string exit,
                     string edit, string undo, string redo, string cut, string copy, string paste, string del, string find,
                     string findNext, string findPrev, string replace, string goTo, string selectAll, string timeDate,
                     string format, string wordWrap, string view, string zoom, string zoomIn, string zoomOut, string restoreZoom,
                     string statusBar, string language, string autoLang, string help, string about, string startTyping, string untitled,
                     string encSave, string decOpen, string encDoc, string decDoc, string encSub, string decSub, string passEmpty, string passMismatch,
                     string passLabel, string confirmPassLabel, string enterPass, string repeatPass,
                     string secTitle, string secContent, string encChoice, string txtChoice,
                     string saveChanges, string dontSave, string cannotFind, string replaceDone, string lineNum, string lineBeyond, string visitWeb, string decFail,
                     string cancelStr, string okStr, string aboutContentStr)
        {
            map[code] = new Dictionary<string, string>
            {
                { "File", file }, { "New", newDoc }, { "NewWindow", newWin }, { "Open", open },
                { "Save", save }, { "SaveAs", saveAs }, { "Exit", exit },
                { "Edit", edit }, { "Undo", undo }, { "Redo", redo }, { "Cut", cut }, { "Copy", copy },
                { "Paste", paste }, { "Delete", del }, { "Find", find }, { "FindNext", findNext },
                { "FindPrev", findPrev }, { "Replace", replace }, { "GoTo", goTo },
                { "SelectAll", selectAll }, { "TimeDate", timeDate },
                { "Format", format }, { "WordWrap", wordWrap },
                { "View", view }, { "Zoom", zoom }, { "ZoomIn", zoomIn }, { "ZoomOut", zoomOut },
                { "RestoreDefaultZoom", restoreZoom }, { "StatusBar", statusBar },
                { "Language", language }, { "AutoLanguage", autoLang },
                { "Help", help }, { "About", about },
                { "StartTyping", startTyping }, { "Untitled", untitled },
                { "FindPlaceholder", "..." }, { "ReplacePlaceholder", "..." },
                { "MatchCase", "Match Case" }, { "ReplaceBtn", replace }, { "ReplaceAllBtn", replace },
                { "OK", okStr }, { "Cancel", cancelStr }, { "Yes", "Yes" }, { "No", "No" },
                { "Success", "Success" }, { "Error", "Error" },
                { "LnCol", "Ln {0}, Col {1}" },
                { "EncryptSave", encSave }, { "EncryptAndSave", encSave },
                { "DecryptOpen", decOpen }, { "DecryptAndOpen", decOpen },
                { "EncryptDoc", encDoc }, { "EncryptDocument", encDoc },
                { "DecryptDoc", decDoc }, { "DecryptDocument", decDoc },
                { "EncryptSubtitle", encSub }, { "SetPasswordPrompt", encSub },
                { "DecryptSubtitle", decSub }, { "EnterPasswordPrompt", decSub },
                { "PasswordLabel", passLabel }, { "ConfirmPasswordLabel", confirmPassLabel },
                { "EnterPassword", enterPass }, { "RepeatPassword", repeatPass },
                { "PasswordEmptyError", passEmpty }, { "PasswordMismatchError", passMismatch },
                { "SecurityVerification", encDoc },
                { "SaveDocumentSecurityTitle", secTitle }, { "SaveDocumentSecurityContent", secContent },
                { "EncryptedDhinChoice", encChoice }, { "PlainTextTxtChoice", txtChoice },
                { "NotelockTitle", "Notelock" }, { "SaveChangesTitle", "Notelock" },
                { "SaveChangesPrompt", saveChanges }, { "DontSave", dontSave },
                { "CannotFind", cannotFind }, { "ReplaceAllDone", replaceDone },
                { "GoToLineTitle", goTo }, { "LineNumberLabel", lineNum },
                { "LineNumberPlaceholder", lineNum }, { "LineBeyondTotal", lineBeyond },
                { "AboutNotelockTitle", about }, { "VisitWebsite", visitWeb },
                { "DecryptionFailed", decFail }, { "AboutContent", aboutContentStr }
            };
        }

        AddLang("en", "File", "New", "New Window", "Open...", "Save", "Save As...", "Exit", "Edit", "Undo", "Redo", "Cut", "Copy", "Paste", "Delete", "Find...", "Find Next", "Find Previous", "Replace...", "Go To...", "Select All", "Time/Date", "Format", "Word Wrap", "View", "Zoom", "Zoom In", "Zoom Out", "Restore Default Zoom", "Status Bar", "Language", "Auto (System Language)", "Help", "About Notelock", "Start typing...", "Untitled", "Encrypt & Save", "Decrypt & Open", "Encrypt Document", "Decrypt Document", "Set a strong password to protect your file's content.", "Enter your password to unlock the encrypted document.", "Password cannot be empty", "Passwords do not match", "Password", "Confirm Password", "Enter password", "Confirm password", "Save Document Security", "Choose how you would like to save your document:\n\n🔒 Encrypted Document (.dhin)\nProtects content with a password so only authorized users can open it.\n\n📄 Plain Text Document (.txt)\nStandard unencrypted file accessible by any text editor.", "🔒 Encrypted (.dhin)", "📄 Plain Text (.txt)", "Do you want to save changes to this document?", "Don't Save", "Cannot find \"{0}\"", "All occurrences replaced.", "Line number", "The line number is beyond the total number of lines.", "Visit Website", "Decryption failed. Invalid password or corrupted file.", "Cancel", "OK", "Notelock Secure Text Editor\nVersion 3.0\n\nDeveloped by Dhinovatech - Visit website - https://www.dhinovatech.com\n\nFeatures:\n- Windows 10 Notepad compatibility\n- AES-256 Encrypted Documents (.dhin)\n- Premium Security UI");
        AddLang("zh-CN", "文件", "新建", "新窗口", "打开...", "保存", "另存为...", "退出", "编辑", "撤销", "重做", "剪切", "复制", "粘贴", "删除", "查找...", "查找下一个", "查找上一个", "替换...", "转到...", "全选", "时间/日期", "格式", "自动换行", "视图", "缩放", "放大", "缩小", "恢复默认缩放", "状态栏", "语言", "自动（系统语言）", "帮助", "关于 Notelock", "开始输入...", "无标题", "加密并保存", "解密并打开", "加密文档", "解密文档", "设置强密码以保护您的文件内容。", "输入密码以解锁受保护的文档。", "密码不能为空", "密码不匹配", "密码", "确认密码", "请输入密码", "请再次输入密码", "保存文档安全设置", "请选择保存文档的方式：\n\n🔒 加密文档 (.dhin)\n使用密码保护内容，仅授权用户可打开。\n\n📄 明文文档 (.txt)\n任何文本编辑器均可访问的标准未加密文件。", "🔒 加密 (.dhin)", "📄 明文 (.txt)", "是否要保存对此文档的更改？", "不保存", "找不到 \"{0}\"", "所有匹配项均已替换。", "行号", "行号超出总行数。", "访问网站", "解密失败。密码无效或文件损坏。", "取消", "确定", "Notelock 安全文本编辑器\n版本 3.0\n\n由 Dhinovatech 开发 - 访问网站 - https://www.dhinovatech.com\n\n特性：\n- 兼容 Windows 10 记事本\n- AES-256 加密文档 (.dhin)\n- 高级安全 UI");
        AddLang("hi", "फ़ाइल", "नया", "नई विंडो", "खोलें...", "सहेजें", "ऐसे सहेजें...", "बाहर निकलें", "संपादित करें", "पूर्वावत करें", "पुनरावृत्ति करें", "कट", "कॉपी", "पेस्ट", "हटाएं", "खोजें...", "अगला खोजें", "पिछला खोजें", "बदलें...", "इस लाइन पर जाएं...", "सभी चुनें", "समय/तिथि", "प्रारूप", "शब्द लपेटें", "देखें", "ज़ूम", "ज़ूम इन", "ज़ूम आउट", "डिफ़ॉल्ट ज़ूम रीसेट करें", "स्थिति पट्टी", "भाषा", "ऑटो (सिस्टम भाषा)", "सहायता", "Notelock के बारे में", "टाइप करना शुरू करें...", "बिना शीर्षक", "एन्क्रिप्ट और सहेजें", "डीक्रिप्ट और खोलें", "दस्तावेज़ एन्क्रिप्ट करें", "दस्तावेज़ डीक्रिप्ट करें", "अपनी फ़ाइल की सुरक्षा के लिए पासवर्ड सेट करें।", "दस्तावेज़ खोलने के लिए पासवर्ड दर्ज करें।", "पासवर्ड खाली नहीं हो सकता", "पासवर्ड मेल नहीं खाते", "पासवर्ड", "पासवर्ड की पुष्टि करें", "पासवर्ड दर्ज करें", "पासवर्ड दोबारा दर्ज करें", "दस्तावेज़ सुरक्षा सहेजें", "चुनें कि आप अपना दस्तावेज़ कैसे सहेजना चाहते हैं:\n\n🔒 एन्क्रिप्टेड दस्तावेज़ (.dhin)\nपासवर्ड से सामग्री को सुरक्षित करता है।\n\n📄 प्लेन टेक्स्ट दस्तावेज़ (.txt)\nमानक गैर-एन्क्रिप्टेड फ़ाइल।", "🔒 एन्क्रिप्टेड (.dhin)", "📄 प्लेन टेक्स्ट (.txt)", "क्या आप इस दस्तावेज़ में बदलाव सहेजना चाहते हैं?", "सहेजें नहीं", "\"{0}\" नहीं मिला", "सभी स्थान बदल दिए गए।", "लाइन संख्या", "लाइन संख्या कुल लाइनों से अधिक है।", "वेबसाइट पर जाएं", "डीक्रिप्शन विफल। अमान्य पासवर्ड या दूषित फ़ाइल।", "रद्द करें", "ठीक है", "Notelock सुरक्षित पाठ संपादक\nसंस्करण 3.0\n\nDhinovatech द्वारा विकसित - वेबसाइट देखें - https://www.dhinovatech.com\n\nविशेषताएं:\n- विंडोज 10 नोटपैड संगतता\n- AES-256 एन्क्रिप्टेड दस्तावेज़ (.dhin)\n- प्रीमियम सुरक्षा UI");
        AddLang("es", "Archivo", "Nuevo", "Nueva ventana", "Abrir...", "Guardar", "Guardar como...", "Salir", "Edición", "Deshacer", "Rehacer", "Cortar", "Copiar", "Pegar", "Eliminar", "Buscar...", "Buscar siguiente", "Buscar anterior", "Reemplazar...", "Ir a...", "Seleccionar todo", "Hora/Fecha", "Formato", "Ajuste de línea", "Ver", "Zoom", "Acercar", "Alejar", "Restablecer zoom", "Barra de estado", "Idioma", "Automático (Idioma del sistema)", "Ayuda", "Acerca de Notelock", "Empieza a escribir...", "Sin título", "Encriptar y guardar", "Desencriptar y abrir", "Encriptar documento", "Desencriptar documento", "Establezca una contraseña para proteger el archivo.", "Ingrese su contraseña para desbloquear el documento.", "La contraseña no puede estar vacía", "Las contraseñas no coinciden", "Contraseña", "Confirmar contraseña", "Ingrese la contraseña", "Confirme la contraseña", "Seguridad al guardar documento", "Elija cómo desea guardar su documento:\n\n🔒 Documento encriptado (.dhin)\nProtege el contenido con contraseña.\n\n📄 Documento de texto plano (.txt)\nArchivo normal no encriptado.", "🔒 Encriptado (.dhin)", "📄 Texto plano (.txt)", "¿Desea guardar los cambios en este documento?", "No guardar", "No se puede encontrar \"{0}\"", "Se han reemplazado todas las coincidencias.", "Número de línea", "El número de línea supera el total de líneas.", "Visitar sitio web", "Error de desencriptación. Contraseña no válida.", "Cancelar", "Aceptar", "Editor de texto seguro Notelock\nVersión 3.0\n\nDesarrollado por Dhinovatech - Visitar sitio web - https://www.dhinovatech.com\n\nCaracterísticas:\n- Compatibilidad con el Bloc de notas de Windows 10\n- Documentos encriptados AES-256 (.dhin)\n- Interfaz de seguridad prémium");
        AddLang("fr", "Fichier", "Nouveau", "Nouvelle fenêtre", "Ouvrir...", "Enregistrer", "Enregistrer sous...", "Quitter", "Édition", "Annuler", "Rétablir", "Couper", "Copier", "Coller", "Supprimer", "Rechercher...", "Rechercher le suivant", "Rechercher le précédent", "Remplacer...", "Aller à...", "Sélectionner tout", "Heure/Date", "Format", "Retour automatique à la ligne", "Affichage", "Zoom", "Zoom avant", "Zoom arrière", "Restaurer le zoom par défaut", "Barre d'état", "Langue", "Auto (Langue du système)", "Aide", "À propos de Notelock", "Commencez à saisir...", "Sans titre", "Chiffrer et enregistrer", "Déchiffrer et ouvrir", "Chiffrer le document", "Déchiffrer le document", "Définissez un mot de passe pour protéger votre fichier.", "Entrez le mot de passe pour déverrouiller le document.", "Le mot de passe ne peut pas être vide", "Les mots de passe ne correspondent pas", "Mot de passe", "Confirmer le mot de passe", "Entrez le mot de passe", "Confirmez le mot de passe", "Sécurité d'enregistrement du document", "Choisissez comment vous souhaitez enregistrer votre document :\n\n🔒 Document chiffré (.dhin)\nProtège le contenu par mot de passe.\n\n📄 Document texte brut (.txt)\nFichier standard non chiffré.", "🔒 Chiffré (.dhin)", "📄 Texte brut (.txt)", "Voulez-vous enregistrer les modifications apportées à ce document ?", "Ne pas enregistrer", "Impossible de trouver \"{0}\"", "Toutes les occurrences ont été remplacées.", "Numéro de ligne", "Le numéro de ligne dépasse le nombre total de lignes.", "Visiter le site web", "Échec du déchiffrement. Mot de passe invalide.", "Annuler", "OK", "Éditeur de texte sécurisé Notelock\nVersion 3.0\n\nDéveloppé par Dhinovatech - Visiter le site web - https://www.dhinovatech.com\n\nFonctionnalités :\n- Compatibilité Bloc-notes Windows 10\n- Documents chiffrés AES-256 (.dhin)\n- Interface de sécurité haut de gamme");
        AddLang("ar", "ملف", "جديد", "نافذة جديدة", "فتح...", "حفظ", "حفظ باسم...", "خروج", "تحرير", "التراجع", "إعادة", "قص", "نسخ", "لصق", "حذف", "بحث...", "البحث عن التالي", "البحث عن السابق", "استبدال...", "الانتقال إلى...", "تحديد الكل", "الوقت/التاريخ", "تنسيق", "التفاف النص", "عرض", "تكبير/تصغير", "تكبير", "تصغير", "استعادة التكبير الافتراضي", "شريط الحالة", "اللغة", "تلقائي (لغة النظام)", "تعليمات", "حول Notelock", "ابدأ الكتابة...", "بلا عنوان", "تشفير وحفظ", "فك التشفير وفتح", "تشفير المستند", "فك تشفير المستند", "تعيين كلمة مرور لحماية الملف.", "أدخل كلمة المرور لفتح المستند.", "لا يمكن أن تكون كلمة المرور فارغة", "كلمات المرور غير متطابقة", "كلمة المرور", "تأكيد كلمة المرور", "أدخل كلمة المرور", "أعد إدخال كلمة المرور", "أمان حفظ المستند", "اختر كيفية حفظ المستند:\n\n🔒 مستند مشفر (.dhin)\nيحمي المحتوى بكلمة مرور.\n\n📄 مستند نصي عادي (.txt)\nملف عادي غير مشفر.", "🔒 مشفر (.dhin)", "📄 نص عادي (.txt)", "هل تريد حفظ التغييرات على هذا المستند؟", "عدم الحفظ", "تعذر العثور على \"{0}\"", "تم استبدال جميع المطابقات.", "رقم السطر", "رقم السطر يتجاوز إجمالي عدد الأسطر.", "زيارة الموقع الإلكتروني", "فشل فك التشفير. كلمة المرور غير صالحة.", "إلغاء", "موافق", "محرر النصوص الآمن Notelock\nالإصدار 3.0\n\nتطوير Dhinovatech - زيارة الموقع الإلكتروني - https://www.dhinovatech.com\n\nالميزات:\n- توافق مع مفكرة Windows 10\n- مستندات مشفرة بـ AES-256 (.dhin)\n- واجهة أمان ممتازة");
        AddLang("bn", "ফাইল", "নতুন", "নতুন উইন্ডো", "খুলুন...", "সংরক্ষণ", "নতুন নামে সংরক্ষণ...", "প্রস্থান", "সম্পাদনা", "পূর্বাবস্থায় ফেরান", "পুনরায় করুন", "কাট", "কপি", "পেস্ট", "মুছুন", "খুঁজুন...", "পরবর্তী খুঁজুন", "পূর্ববর্তী খুঁজুন", "প্রতিস্থাপন...", "নির্দিষ্ট লাইনে যান...", "সব নির্বাচন করুন", "সময়/তারিখ", "বিন্যাস", "ওয়ার্ড র‍্যাপ", "দৃশ্য", "জুম", "জুম ইন", "জুম আউট", "ডিফল্ট জুম রিসেট করুন", "স্ট্যাটাস বার", "ভাষা", "অটো (সিস্টেম ভাষা)", "সাহায্য", "Notelock সম্পর্কে", "টাইপ করা শুরু করুন...", "শিরোনামহীন", "এনক্রিপ্ট ও সেভ করুন", "ডিক্রিপ্ট ও খুলুন", "ডকুমেন্ট এনক্রিপ্ট করুন", "ডকুমেন্ট ডিক্রিপ্ট করুন", "ফাইল সুরক্ষার জন্য পাসওয়ার্ড সেট করুন।", "পাসওয়ার্ড দিয়ে ফাইল খুলুন।", "পাসওয়ার্ড ফাঁকা হতে পারে না", "পাসওয়ার্ড মেলেনি", "পাসওয়ার্ড", "পাসওয়ার্ড নিশ্চিত করুন", "পাসওয়ার্ড লিখুন", "পাসওয়ার্ড আবার লিখুন", "ডকুমেন্ট সুরক্ষা সংরক্ষণ", "ডকুমেন্ট কীভাবে সংরক্ষণ করবেন তা নির্বাচন করুন:\n\n🔒 এনক্রিপ্টেড ডকুমেন্ট (.dhin)\nপাসওয়ার্ড দিয়ে সুরক্ষিত।\n\n📄 সাধারণ টেক্সট ডকুমেন্ট (.txt)\nসাধারণ ফাইল।", "🔒 এনক্রিপ্টেড (.dhin)", "📄 সাধারণ টেক্সট (.txt)", "আপনি কি এই ডকুমেন্টের পরিবর্তনগুলি সংরক্ষণ করতে চান?", "সংরক্ষণ করবেন না", "\"{0}\" পাওয়া যায়নি", "সবগুলি প্রতিস্থাপিত হয়েছে।", "লাইন নম্বর", "লাইন নম্বর মোট লাইনের চেয়ে বেশি।", "ওয়েবসাইট দেখুন", "ডিক্রিপশন ব্যর্থ হয়েছে। ভুল পাসওয়ার্ড।", "বাতিল", "ঠিক আছে", "Notelock সুরক্ষিত টেক্সট এডিটর\nসংস্করণ 3.0\n\nDhinovatech দ্বারা তৈরি - ওয়েবসাইট দেখুন - https://www.dhinovatech.com\n\nবৈশিষ্ট্য:\n- উইন্ডোজ 10 নোটপ্যাড সামঞ্জস্য\n- AES-256 এনক্রিপ্টেড ডকুমেন্ট (.dhin)\n- প্রিমিয়াম নিরাপত্তা UI");
        AddLang("pt", "Ficheiro", "Novo", "Nova janela", "Abrir...", "Guardar", "Guardar como...", "Sair", "Editar", "Desfazer", "Refazer", "Cortar", "Copiar", "Colar", "Eliminar", "Localizar...", "Localizar seguinte", "Localizar anterior", "Substituir...", "Ir para...", "Selecionar tudo", "Hora/Data", "Formatar", "Quebra de linha", "Ver", "Zoom", "Ampliar", "Reduzir", "Restaurar zoom padrão", "Barra de estado", "Idioma", "Automático (Idioma do sistema)", "Ajuda", "Sobre o Notelock", "Comece a digitar...", "Sem título", "Encriptar e guardar", "Desencriptar e abrir", "Encriptar documento", "Desencriptar documento", "Defina uma palavra-passe para proteger o ficheiro.", "Introduza a palavra-passe para desbloquear.", "A palavra-passe não pode estar vazia", "As palavras-passe não coincidem", "Palavra-passe", "Confirmar palavra-passe", "Introduza a palavra-passe", "Confirme a palavra-passe", "Segurança ao guardar documento", "Escolha como deseja guardar o seu documento:\n\n🔒 Documento encriptado (.dhin)\nProtege o conteúdo com palavra-passe.\n\n📄 Documento em texto simples (.txt)\nFicheiro normal não encriptado.", "🔒 Encriptado (.dhin)", "📄 Texto simples (.txt)", "Deseja guardar as alterações a este documento?", "Não guardar", "Não foi possível localizar \"{0}\"", "Todas as ocorrências foram substituídas.", "Número da linha", "O número da linha excede o total de linhas.", "Visitar o site", "Falha ao desencriptar. Palavra-passe inválida.", "Cancelar", "OK", "Editor de Texto Seguro Notelock\nVersão 3.0\n\nDesenvolvido por Dhinovatech - Visite o site - https://www.dhinovatech.com\n\nFuncionalidades:\n- Compatibilidade com o Bloco de Notas do Windows 10\n- Documentos Encriptados AES-256 (.dhin)\n- Interface de Segurança Premium");
        AddLang("ru", "Файл", "Создать", "Новое окно", "Открыть...", "Сохранить", "Сохранить как...", "Выход", "Правка", "Отменить", "Повторить", "Вырезать", "Копировать", "Вставить", "Удалить", "Найти...", "Найти далее", "Найти ранее", "Заменить...", "Перейти...", "Выделить всё", "Время/Дата", "Формат", "Перенос по словами", "Вид", "Масштаб", "Увеличить", "Уменьшить", "Сбросить масштаб", "Строка состояния", "Язык", "Авто (Язык системы)", "Справка", "О программе Notelock", "Начните ввод...", "Без имени", "Зашифровать и сохранить", "Расшифровать и открыть", "Зашифровать документ", "Расшифровать документ", "Задайте пароль для защиты файла.", "Введите пароль для открытия файла.", "Пароль не может быть пустым", "Пароли не совпадают", "Пароль", "Подтвердите пароль", "Введите пароль", "Повторите пароль", "Защита сохранения документа", "Выберите способ сохранения документа:\n\n🔒 Зашифрованный документ (.dhin)\nЗащищает содержимое паролем.\n\n📄 Обычный текстовый документ (.txt)\nСтандартный незашифрованный файл.", "🔒 Зашифрованный (.dhin)", "📄 Обычный текст (.txt)", "Сохранить изменения в этом документе?", "Не сохранять", "Не удается найти \"{0}\"", "Все совпадения заменены.", "Номер строки", "Номер строки превышает общее число строк.", "Посетить веб-сайт", "Сбой расшифровки. Неверный пароль.", "Отмена", "ОК", "Защищенный текстовый редактор Notelock\nВерсия 3.0\n\nРазработано Dhinovatech - Посетите веб-сайт - https://www.dhinovatech.com\n\nВозможности:\n- Совместимость с Блокнотом Windows 10\n- Зашифрованные документы AES-256 (.dhin)\n- Премиальный интерфейс безопасности");
        AddLang("ur", "فائل", "نیا", "نئی ونڈو", "کھولیں...", "محفوظ کریں", "نام سے محفوظ کریں...", "باہر نکلیں", "ترمیم", "پہلے جیسا کریں", "دوبارہ کریں", "کاٹیں", "کاپی", "پیسٹ", "حذف کریں", "تلاش کریں...", "اگلا تلاش کریں", "پچھلا تلاش کریں", "تبدیل کریں...", "لائن پر جائیں...", "سب منتخب کریں", "وقت/تاریخ", "فارمیٹ", "ورڈ ریپ", "دیکھیں", "زوم", "زوم ان", "زوم آؤٹ", "ڈیفالٹ زوم ری سیٹ کریں", "اسٹیٹس بار", "زبان", "خودکار (سستم کی زبان)", "مدد", "Notelock کے بارے میں", "ٹائپ کرنا شروع کریں...", "بغیر عنوان", "انکرپٹ اور محفوظ کریں", "ڈی کرپٹ اور کھولیں", "دستاویز انکرپٹ کریں", "دستاویز ڈی کرپٹ کریں", "فائل کو محفوظ کرنے کے لیے پاس ورڈ لگائیں۔", "پاس ورڈ درج کریں۔", "پاس ورڈ خالی نہیں ہو سکتا", "پاس ورڈ مطابقت نہیں رکھتے", "پاس ورڈ", "پاس ورڈ کی تصدیق کریں", "پاس ورڈ درج کریں", "پاس ورڈ دوبارہ درج کریں", "دستاویز کی حفاظت کے ساتھ محفوظ کریں", "دستاویز محفوظ کرنے کا طریقہ منتخب کریں:\n\n🔒 انکرپٹڈ دستاویز (.dhin)\nپاس ورڈ سے مواد محفوظ کرتا ہے۔\n\n📄 سادہ ٹیکسٹ دستاویز (.txt)\nسادہ غیر انکرپٹڈ فائل۔", "🔒 انکرپٹڈ (.dhin)", "📄 سادہ ٹیکسٹ (.txt)", "کیا آپ اس دستاویز میں تبدیلیاں محفوظ کرنا چاہتے ہیں؟", "محفوظ نہ کریں", "\"{0}\" نہیں ملا", "تمام الفاظ تبدیل کر دیے گئے۔", "لائن نمبر", "لائن نمبر کل لائنوں سے زیادہ ہے۔", "ویب سائٹ پر جائیں", "ڈی کرپشن ناکام ہو گئی۔ پاس ورڈ غلط ہے۔", "منسوخ کریں", "ٹھیک ہے", "Notelock محفوظ ٹیکسٹ ایڈیٹر\nورژن 3.0\n\nDhinovatech کے ذریعہ تیار کردہ - ویب سائٹ دیکھیں - https://www.dhinovatech.com\n\nخصوصیات:\n- ونڈوز 10 نوٹ پیڈ مطابقت\n- AES-256 انکرپٹڈ دستاویزات (.dhin)\n- پریمیئم سیکیورٹی UI");
        AddLang("id", "Berkas", "Baru", "Jendela Baru", "Buka...", "Simpan", "Simpan Sebagai...", "Keluar", "Edit", "Urungkan", "Ulangi", "Potong", "Salin", "Tempel", "Hapus", "Cari...", "Cari Berikutnya", "Cari Sebelumnya", "Ganti...", "Buka Baris...", "Pilih Semua", "Waktu/Tanggal", "Format", "Bungkus Teks", "Tampilan", "Zoom", "Perbesar", "Perkecil", "Pulihkan Zoom Default", "Bilah Status", "Bahasa", "Otomatis (Bahasa Sistem)", "Bantuan", "Tentang Notelock", "Mulai mengetik...", "Tanpa Judul", "Enkripsi & Simpan", "Dekripsi & Buka", "Enkripsi Dokumen", "Dekripsi Dokumen", "Buat kata sandi untuk melindungi berkas.", "Masukkan kata sandi untuk membuka.", "Kata sandi tidak boleh kosong", "Kata sandi tidak cocok", "Kata Sandi", "Konfirmasi Kata Sandi", "Masukkan kata sandi", "Ulangi kata sandi", "Keamanan Menyimpan Dokumen", "Pilih cara menyimpan dokumen Anda:\n\n🔒 Dokumen Terenkripsi (.dhin)\nMelindungi konten dengan kata sandi.\n\n📄 Dokumen Teks Biasa (.txt)\nBerkas standar tanpa enkripsi.", "🔒 Terenkripsi (.dhin)", "📄 Teks Biasa (.txt)", "Apakah Anda ingin menyimpan perubahan pada dokumen ini?", "Jangan Simpan", "Tidak dapat menemukan \"{0}\"", "Semua kemunculan telah diganti.", "Nomor baris", "Nomor baris melebihi total baris.", "Kunjungi Situs Web", "Gagal mendekripsi. Kata sandi salah.", "Batal", "OK", "Editor Teks Aman Notelock\nVersi 3.0\n\nDikembangkan oleh Dhinovatech - Kunjungi situs web - https://www.dhinovatech.com\n\nFitur:\n- Kompatibilitas Notepad Windows 10\n- Dokumen Terenkripsi AES-256 (.dhin)\n- UI Keamanan Premium");
        AddLang("de", "Datei", "Neu", "Neues Fenster", "Öffnen...", "Speichern", "Speichern unter...", "Beenden", "Bearbeiten", "Rückgängig", "Wiederholen", "Ausschneiden", "Kopieren", "Einfügen", "Löschen", "Suchen...", "Weitersuchen", "Rückwärts suchen", "Ersetzen...", "Gehe zu...", "Alles auswählen", "Uhrzeit/Datum", "Format", "Zeilenumbruch", "Ansicht", "Zoom", "Vergrößern", "Verkleinern", "Standardzoom wiederherstellen", "Statusleiste", "Sprache", "Auto (Systemsprache)", "Hilfe", "Info über Notelock", "Beginnen Sie zu tippen...", "Unbenannt", "Verschlüsseln & Speichern", "Entschlüsseln & Öffnen", "Dokument verschlüsseln", "Dokument entschlüsseln", "Legen Sie ein Passwort fest.", "Geben Sie das Passwort ein.", "Passwort darf nicht leer sein", "Passwörter stimmen nicht überein", "Passwort", "Passwort bestätigen", "Passwort eingeben", "Passwort wiederholen", "Dokumentensicherheit beim Speichern", "Wählen Sie, wie Sie Ihr Dokument speichern möchten:\n\n🔒 Verschlüsseltes Dokument (.dhin)\nSchützt den Inhalt mit einem Passwort.\n\n📄 Reine Textdatei (.txt)\nStandardmäßige unverschlüsselte Datei.", "🔒 Verschlüsselt (.dhin)", "📄 Reiner Text (.txt)", "Möchten Sie die Änderungen an diesem Dokument speichern?", "Nicht speichern", "\"{0}\" kann nicht gefunden werden.", "Alle Vorkommen wurden ersetzt.", "Zeilennummer", "Die Zeilennummer liegt außerhalb der Gesamtzahl der Zeilen.", "Website besuchen", "Entschlüsselung fehlgeschlagen. Ungültiges Passwort.", "Abbrechen", "OK", "Sicherer Texteditor Notelock\nVersion 3.0\n\nEntwickelt von Dhinovatech - Website besuchen - https://www.dhinovatech.com\n\nFunktionen:\n- Kompatibilität mit Windows 10 Editor\n- AES-256 verschlüsselte Dokumente (.dhin)\n- Premium-Sicherheits-UI");
        AddLang("ja", "ファイル", "新規", "新しいウィンドウ", "開く...", "保存", "名前を付けて保存...", "終了", "編集", "元に戻す", "やり直し", "切り取り", "コピー", "貼り付け", "削除", "検索...", "次を検索", "前を検索", "置換...", "行へ移動...", "すべて選択", "日付と時刻", "書式", "右端で折り返す", "表示", "拡大/縮小", "拡大", "縮小", "既定の拡大率に戻す", "ステータス バー", "言語", "自動 (システム言語)", "ヘルプ", "Notelock について", "入力を開始...", "無題", "暗号化して保存", "復号して開く", "ドキュメントを暗号化", "ドキュメントを復号", "ファイルを保護するパスワードを設定します。", "パスワードを入力してください。", "パスワードを入力してください", "パスワードが一致しません", "パスワード", "パスワードの確認", "パスワードを入力", "パスワードを再入力", "ドキュメントの保存セキュリティ", "ドキュメントの保存方法を選択してください:\n\n🔒 暗号化ドキュメント (.dhin)\nパスワードでコンテンツを保護します。\n\n📄 プレーンテキスト (.txt)\n標準の非暗号化ファイル。", "🔒 暗号化 (.dhin)", "📄 プレーンテキスト (.txt)", "このドキュメントへの変更を保存しますか？", "保存しない", "\"{0}\" が見つかりません", "すべての該当箇所を置換しました。", "行番号", "行番号が総行数を超えています。", "ウェブサイトを訪問", "復号に失敗しました。パスワードが無効です。", "キャンセル", "OK", "Notelock セキュアテキストエディタ\nバージョン 3.0\n\nDhinovatech 開発 - ウェブサイトを見る - https://www.dhinovatech.com\n\n機能:\n- Windows 10 メモ帳互換性\n- AES-256 暗号化ドキュメント (.dhin)\n- プレミアムセキュリティ UI");
        AddLang("pcm", "File", "New", "New Window", "Open...", "Save", "Save As...", "Comot", "Edit", "Undo", "Redo", "Cut", "Copy", "Paste", "Delete", "Find...", "Find Next", "Find Previous", "Replace...", "Go To...", "Select All", "Time/Date", "Format", "Word Wrap", "View", "Zoom", "Zoom In", "Zoom Out", "Restore Normal Zoom", "Status Bar", "Language", "Auto (System Language)", "Help", "About Notelock", "Start to type...", "No Title", "Encrypt & Save", "Decrypt & Open", "Encrypt Document", "Decrypt Document", "Put strong password to protect your file.", "Enter password make file open.", "Password no fit dey empty", "Passwords no match", "Password", "Confirm Password", "Enter password", "Repeat password", "Save Document Security", "Choose how you wan save your document:\n\n🔒 Encrypted Document (.dhin)\nProtect am with password.\n\n📄 Plain Text Document (.txt)\nNormal text file.", "🔒 Encrypted (.dhin)", "📄 Plain Text (.txt)", "You wan save change to dis document?", "No Save", "No fit find \"{0}\"", "All of dem don change finish.", "Line number", "Line number pass the total lines.", "Visit Website", "Decryption fail. Password wrong.", "Cancel", "OK", "Notelock Secure Text Editor\nVersion 3.0\n\nDhinovatech make am - Visit website - https://www.dhinovatech.com\n\nFeatures:\n- Windows 10 Notepad style\n- AES-256 Encrypted Documents (.dhin)\n- Premium Security UI");
        AddLang("arz", "ملف", "جديد", "شباك جديد", "فتح...", "حفظ", "حفظ باسم...", "خروج", "تعديل", "تراجع", "إعادة", "قص", "نسخ", "لزق", "مسح", "تدوير...", "تدبيس الجاي", "تدبيس اللي فات", "تبديل...", "روح لـ...", "علم الكل", "الوقت/التاريخ", "تنسيق", "لف الكلام", "عرض", "زوم", "كبر", "صغر", "رجع الزوم", "شريط الحالة", "اللغة", "تلقائي (لغة السيستم)", "مساعدة", "عن Notelock", "ابدأ اكتب...", "من غير عنوان", "تشفير وحفظ", "فك تشفير وفتح", "تشفير الملف", "فك تشفير الملف", "اكتب باسوورد عشان تحمي الملف.", "اكتب الباسوورد عشان تفتح.", "الباسوورد ماينفعش يكون فاضي", "الباسووردات مش زي بعض", "الباسوورد", "تأكيد الباسوورد", "اكتب الباسوورد", "اكتب الباسوورد تاني", "أمان حفظ الملف", "اختار تحفظ الملف إزاي:\n\n🔒 ملف مشفر (.dhin)\nبيحمي الكلام بباسوورد.\n\n📄 ملف كلام عادي (.txt)\nملف عادي من غير تشفير.", "🔒 مشفر (.dhin)", "📄 كلام عادي (.txt)", "عايز تحفظ التغييرات دي؟", "متنزلش حفظ", "مش لاقي \"{0}\"", "كلهم اتغيروا خلااص.", "رقم السطر", "رقم السطر عدى السطور كلها.", "زور الموقع", "فك التشفير باظ. الباسوورد غلط.", "إلغاء", "ماشي", "محرر النصوص الآمن Notelock\nإصدار 3.0\n\nتطوير Dhinovatech - زور الموقع - https://www.dhinovatech.com\n\nالمميزات:\n- متوافق مع نوت باد Windows 10\n- ملفات مشفرة بـ AES-256 (.dhin)\n- واجهة أمان عالية");
        AddLang("mr", "फाईल", "नवीन", "नवीन विंडो", "उघडा...", "जतन करा", "असे जतन करा...", "बाहर पडा", "संपादीत करा", "पूर्ववत करा", "पुन्हा करा", "कापा", "कॉपी करा", "पेस्ट करा", "हटवा", "शोधा...", "पुढील शोधा", "मागील शोधा", "बदला...", "या ओळीवर जा...", "सर्व निवडा", "वेळ/दिनांक", "स्वरूप", "शब्द गुंडाळा", "पहा", "झूम", "झूम इन", "झूम आउट", "डीफॉल्ट झूम रीसेट करा", "स्थिती पट्टी", "भाषा", "ऑटो (सिस्टम भाषा)", "मदत", "Notelock बद्दल", "टाइप करण्यास सुरुवात करा...", "शीर्षकहीन", "एनक्रिप्ट आणि सेव्ह करा", "डिक्रिप्ट आणि उघडा", "दस्तऐवज एनक्रिप्ट करा", "दस्तऐवज डिक्रिप्ट करा", "फाईल सुरक्षित करण्यासाठी पासवर्ड ठेवा.", "उघडण्यासाठी पासवर्ड टाका.", "पासवर्ड रिकामा असू शकत नाही", "पासवर्ड जुळत नाहीत", "पासवर्ड", "पासवर्डची पुष्टी करा", "पासवर्ड टाका", "पासवर्ड पुन्हा टाका", "दस्तऐवज सुरक्षितता जतन करा", "तुमचा दस्तऐवज कसा जतन करायचा ते निवडा:\n\n🔒 एनक्रिप्टेड दस्तऐवज (.dhin)\nपासवर्डने सामग्री सुरक्षित करते.\n\n📄 प्लेन टेक्स्ट दस्तऐवज (.txt)\nसामान्य फाईल.", "🔒 एनक्रिप्टेड (.dhin)", "📄 प्लेन टेक्स्ट (.txt)", "तुम्हाला या दस्तऐवजातील बदल जतन करायचे आहेत का?", "जतन करू नका", "\"{0}\" सापडले नाही", "सर्व ठिकाणचे शब्द बदलले गेले.", "ओळ क्रमांक", "ओळ क्रमांक एकूण ओळींपेक्षा जास्त आहे.", "वेबसाइटला भेट द्या", "डिक्रिप्शन अयशस्वी. अमान्य पासवर्ड.", "रद्द करा", "ठीक आहे", "Notelock सुरक्षित मजकूर संपादक\nआवृत्ती 3.0\n\nDhinovatech द्वारे विकसित - वेबसाइटला भेट द्या - https://www.dhinovatech.com\n\nवैशिष्ट्ये:\n- विंडोज 10 नोटपॅड सुसंगतता\n- AES-256 एन्क्रिप्टेड दस्तऐवज (.dhin)\n- प्रीमियम सुरक्षा UI");
        AddLang("te", "ఫైల్", "కొత్తది", "కొత్త విండో", "తెరవండి...", "సేవ్ చేయండి", "ఇలా సేవ్ చేయండి...", "నిష్క్రమించు", "సవరించు", "రద్దు చేయి", "మళ్లీ చేయి", "కట్ చేయి", "కాపీ", "పేస్ట్", "తొలగించు", "వెతకండి...", "తదుపరి వెతకండి", "మునుపటి వెతకండి", "భర్తీ చేయి...", "లైన్‌కు వెళ్లండి...", "అన్నీ ఎంచుకోండి", "సమయం/తేదీ", "ఫార్మాట్", "వర్డ్ ర్యాప్", "వీక్షణం", "జూమ్", "జూమ్ ఇన్", "జూమ్ అవుట్", "డిఫాల్ట్ జూమ్ రీసెట్ చేయండి", "స్థితి పట్టీ", "భాష", "ఆటో (సిస్టమ్ భాష)", "సహాయం", "Notelock గురించి", "టైప్ చేయడం ప్రారంభించండి...", "శీర్షిక లేనిది", "ఎన్‌క్రిప్ట్ & సేవ్", "డిక్రిప్ట్ & ఓపెన్", "డాక్యుమెంట్ ఎన్‌క్రిప్ట్ చేయండి", "డాక్యుమెంట్ డిక్రిప్ట్ చేయండి", "పాస్‌వర్డ్ సెట్ చేయండి.", "పాస్‌వర్డ్ నమోదు చేయండి.", "పాస్‌వర్డ్ ఖాళీగా ఉండకూడదు", "పాస్‌వర్డ్‌లు సరిపోలలేదు", "పాస్‌వర్డ్", "పాస్‌వర్డ్‌ను నిర్ధారించండి", "పాస్‌వర్డ్ నమోదు చేయండి", "పాస్‌వర్డ్‌ను మళ్లీ నమోదు చేయండి", "డాక్యుమెంట్ భద్రత సేవ్ చేయండి", "మీ డాక్యుమెంట్‌ను ఎలా సేవ్ చేయాలో ఎంచుకోండి:\n\n🔒 ఎన్‌క్రిప్టెడ్ డాక్యుమెంట్ (.dhin)\nపాస్‌వర్డ్‌తో కంటెంట్‌ను రక్షిస్తుంది.\n\n📄 ప్లెయిన్ టెక్స్ట్ డాక్యుమెంట్ (.txt)\nసాధారణ ఫైల్.", "🔒 ఎన్‌క్రిప్టెడ్ (.dhin)", "📄 ప్లెయిన్ టెక్స్ట్ (.txt)", "మీరు ఈ డాక్యుమెంట్‌కు చేసిన మార్పులను సేవ్ చేయాలనుకుంటున్నారా?", "సేవ్ చేయవద్దు", "\"{0}\" కనుగొనబడలేదు", "అన్ని మార్పులు భర్తీ చేయబడ్డాయి.", "లైన్ సంఖ్య", "లైన్ సంఖ్య మొత్తం లైన్ల కంటే ఎక్కువ.", "వెబ్‌సైట్‌ను సందర్శించండి", "డిక్రిప్షన్ విఫలమైంది. తప్పుడు పాస్‌వర్డ్.", "రద్దు చేయి", "సరే", "Notelock సురక్షిత టెక్స్ట్ ఎడిటర్\nవెర్షన్ 3.0\n\nDhinovatech చే అభివృద్ధి చేయబడింది - వెబ్‌సైట్‌ను సందర్శించండి - https://www.dhinovatech.com\n\nలక్షణాలు:\n- విండోస్ 10 నోట్‌ప్యాడ్ అనుకూలత\n- AES-256 ఎన్‌క్రిప్టెడ్ డాక్యుమెంట్‌లు (.dhin)\n- ప్రీమియం సెక్యూరిటీ UI");
        AddLang("tr", "Dosya", "Yeni", "Yeni Pencere", "Aç...", "Kaydet", "Farklı Kaydet...", "Çıkış", "Düzen", "Geri Al", "Yinele", "Kes", "Kopyala", "Yapıştır", "Sil", "Bul...", "Sonrakini Bul", "Öncekini Bul", "Değiştir...", "Git...", "Tümünü Seç", "Saat/Tarih", "Biçim", "Sözcük Kaydır", "Görünüm", "Zum", "Yakınlaştır", "Uzaktır", "Varsayılan Yakınlaştırma", "Durum Çubuğu", "Dil", "Otomatik (Sistem Dili)", "Yardım", "Notelock Hakkında", "Yazmaya başlayın...", "Adsız", "Şifrele ve Kaydet", "Şifreyi Çöz ve Aç", "Belgeyi Şifrele", "Belge Şifresini Çöz", "Dosyayı korumak için şifre belirleyin.", "Kilidi açmak için şifreyi girin.", "Şifre boş olamaz", "Şifreler eşleşmiyor", "Şifre", "Şifreyi Doğrula", "Şifreyi girin", "Şifreyi tekrar girin", "Belge Kaydetme Güvenliği", "Belgenizi nasıl kaydetmek istediğinizi seçin:\n\n🔒 Şifrelenmiş Belge (.dhin)\nİçeriği şifre ile korur.\n\n📄 Düz Metin Belgesi (.txt)\nStandart şifresiz dosya.", "🔒 Şifrelenmiş (.dhin)", "📄 Düz Metin (.txt)", "Bu belgedeki değişiklikleri kaydetmek istiyor musunuz?", "Kaydetme", "\"{0}\" bulunamıyor", "Tüm eşleşmeler değiştirildi.", "Satır numarası", "Satır numarası toplam satır sayısını aşıyor.", "Web Sitesini Ziyaret Et", "Şifre çözme başarısız. Geçersiz şifre.", "İptal", "Tamam", "Notelock Güvenli Metin Düzenleyici\nSürüm 3.0\n\nDhinovatech tarafından geliştirildi - Web sitesini ziyaret edin - https://www.dhinovatech.com\n\nÖzellikler:\n- Windows 10 Not Defteri uyumluluğu\n- AES-256 Şifrelenmiş Belgeler (.dhin)\n- Premium Güvenlik UI");
        AddLang("ta", "கோப்பு", "புதிய", "புதிய சாளரம்", "திற...", "சேமி", "என சேமி...", "வெளியேறு", "திருத்து", "ரத்துசெய்", "மீண்டும் செய்", "வெட்டு", "நகலெடு", "ஒட்டு", "நீக்கு", "தேடு...", "அடுத்ததைத் தேடு", "முந்தையதைத் தேடு", "மாற்று...", "வரியை அடை...", "அனைத்தையும் தேர்ந்தெடு", "நேரம்/தேதி", "வடிவம்", "சொல் மடிப்பு", "பார்", "ஜூம்", "பெரிதாக்கு", "சிறிதாக்கு", "இயல்புநிலைக்கு அமை", "நிலைமைப் பட்டி", "மொழி", "தானியங்கி (அமைப்பின் மொழி)", "உதவி", "Notelock பற்றி", "தட்டச்சு செய்யத் தொடங்குங்கள்...", "தலைப்பில்லாதது", "குறியாக்கம் செய்து சேமி", "குறிவிலக்கம் செய்து திற", "ஆவணத்தை குறியாக்கு", "ஆவணத்தை குறிவிலக்கு", "கடவுச்சொல்லை அமைக்கவும்.", "கடவுச்சொல்லை உள்ளிடவும்.", "கடவுச்சொல் காலியாக இருக்கக்கூடாது", "கடவுச்சொற்கள் பொருந்தவில்லை", "கடவுச்சொல்", "கடவுச்சொல்லை உறுதிப்படுத்தவும்", "கடவுச்சொல்லை உள்ளிடவும்", "கடவுச்சொல்லை மீண்டும் உள்ளிடவும்", "ஆவணப் பாதுகாப்பு சேமிப்பு", "உங்கள் ஆவணத்தைச் சேமிக்கும் முறையைத் தேர்ந்தெடுக்கவும்:\n\n🔒 குறியாக்கப்பட்ட ஆவணம் (.dhin)\nகடவுச்சொல் மூலம் பாதுகாக்கிறது.\n\n📄 சாதாரண உரை ஆவணம் (.txt)\nசாதாரணக் கோப்பு.", "🔒 குறியாக்கப்பட்டது (.dhin)", "📄 சாதாரண உரை (.txt)", "இந்த ஆவணத்தில் செய்யப்பட்ட மாற்றங்களைச் சேமிக்க விரும்புகிறீர்களா?", "சேமிக்க வேண்டாம்", "\"{0}\"-ஐக் கண்டுபிடிக்க முடியவில்லை", "அனைத்து மாற்றங்களும் செய்யப்பட்டன.", "வரி எண்", "வரி எண் மொத்த வரிகளை விட அதிகம்.", "இணையதளத்தைப் பார்வையிடவும்", "குறிவிலக்கம் தோல்வியடைந்தது. தவறான கடவுச்சொல்.", "ரத்துசெய்", "சரி", "Notelock பாதுகாப்பான உரை திருத்தி\nபதிப்பு 3.0\n\nDhinovatech தயாரிப்பு - இணையதளத்தைப் பார்வையிடவும் - https://www.dhinovatech.com\n\nஅம்சங்கள்:\n- விண்டோஸ் 10 நோட்பேட் இணக்கத்தன்மை\n- AES-256 குறியாக்கப்பட்ட ஆவணங்கள் (.dhin)\n- பிரீமியம் பாதுகாப்பு UI");
        AddLang("yue", "檔案", "新建", "新視窗", "開啟...", "儲存", "另存為...", "退出", "編輯", "復原", "重做", "剪下", "複製", "貼上", "刪除", "尋找...", "尋找下一個", "尋找上一個", "替換...", "跳轉到...", "全選", "時間/日期", "格式", "自動換行", "檢視", "縮放", "放大", "縮小", "還原預設縮放", "狀態列", "語言", "自動（系統語言）", "說明", "關於 Notelock", "開始輸入...", "未命名", "加密並儲存", "解密並開啟", "加密文件", "解密文件", "設定密碼保護檔案。", "輸入密碼解鎖。", "密碼不能留空", "密碼唔相符", "密碼", "確認密碼", "輸入密碼", "再一次輸入密碼", "儲存文件安全設定", "選擇您要如何儲存文件：\n\n🔒 加密文件 (.dhin)\n以密碼保護內容。\n\n📄 純文字文件 (.txt)\n一般文字檔案。", "🔒 加密 (.dhin)", "📄 純文字 (.txt)", "要否儲存對此文件的變更？", "不儲存", "搵唔到 \"{0}\"", "所有匹配項已替換。", "行號", "行號超出總行數。", "造訪網站", "解密失敗。密碼無效。", "取消", "確定", "Notelock 安全文字編輯器\n版本 3.0\n\n由 Dhinovatech 開發 - 造訪網站 - https://www.dhinovatech.com\n\n功能：\n- 兼容 Windows 10 記事本\n- AES-256 加密文件 (.dhin)\n- 高級安全 UI");
        AddLang("vi", "Tệp", "Mới", "Cửa sổ mới", "Mở...", "Lưu", "Lưu thành...", "Thoát", "Chỉnh sửa", "Hoàn tác", "Làm lại", "Cắt", "Sao chép", "Dán", "Xóa", "Tìm...", "Tìm tiếp", "Tìm trước", "Thay thế...", "Đi tới dòng...", "Chọn tất cả", "Giờ/Ngày", "Định dạng", "Tự động xuống dòng", "Xem", "Thu phóng", "Phóng to", "Thu nhỏ", "Đặt lại thu phóng mặc định", "Thanh trạng thái", "Ngôn ngữ", "Tự động (Ngôn ngữ hệ thống)", "Trợ giúp", "Giới thiệu về Notelock", "Bắt đầu nhập...", "Không có tiêu đề", "Mã hóa & Lưu", "Giải mã & Mở", "Mã hóa tài liệu", "Giải mã tài liệu", "Đặt mật khẩu bảo vệ tệp.", "Nhập mật khẩu để mở.", "Mật khẩu không được để trống", "Mật khẩu không khớp", "Mật khẩu", "Xác nhận mật khẩu", "Nhập mật khẩu", "Nhập lại mật khẩu", "Bảo mật lưu tài liệu", "Chọn cách bạn muốn lưu tài liệu:\n\n🔒 Tài liệu được mã hóa (.dhin)\nBảo vệ nội dung bằng mật khẩu.\n\n📄 Tài liệu văn bản thuần (.txt)\nTệp tiêu chuẩn không mã hóa.", "🔒 Đã mã hóa (.dhin)", "📄 Văn bản thuần (.txt)", "Bạn có muốn lưu các thay đổi cho tài liệu này không?", "Không lưu", "Không thể tìm thấy \"{0}\"", "Đã thay thế tất cả các mục.", "Số dòng", "Số dòng vượt quá tổng số dòng.", "Truy cập trang web", "Giải mã thất bại. Mật khẩu không hợp lệ.", "Hủy", "OK", "Trình chỉnh sửa văn bản an toàn Notelock\nPhiên bản 3.0\n\nPhát triển bởi Dhinovatech - Truy cập trang web - https://www.dhinovatech.com\n\nTính năng:\n- Tương thích với Windows 10 Notepad\n- Tài liệu mã hóa AES-256 (.dhin)\n- Giao diện bảo mật cao cấp");
        AddLang("wuu", "文件", "新建", "新窗口", "打开...", "保存", "另存为...", "退出", "编辑", "撤销", "重做", "剪切", "复制", "粘贴", "删除", "查找...", "查找下一个", "查找上一个", "替换...", "转到...", "全选", "时间/日期", "格式", "自动换行", "视图", "缩放", "放大", "缩小", "恢复默认缩放", "状态栏", "语言", "自动（系统语言）", "帮助", "关于 Notelock", "开始输入...", "无标题", "加密并保存", "解密并打开", "加密文档", "解密文档", "设置密码保护文件。", "输入密码解锁。", "密码不能为空", "密码不匹配", "密码", "确认密码", "请输入密码", "请再次输入密码", "保存文档安全设置", "请选择保存文档的方式：\n\n🔒 加密文档 (.dhin)\n使用密码保护内容。\n\n📄 明文文档 (.txt)\n标准未加密文件。", "🔒 加密 (.dhin)", "📄 明文 (.txt)", "是否要保存对此文档的更改？", "不保存", "找不到 \"{0}\"", "所有匹配项均已替换。", "行号", "行号超出总行数。", "访问网站", "解密失败。密码无效。", "取消", "确定", "Notelock 安全文本编辑器\n版本 3.0\n\n由 Dhinovatech 开发 - 访问网站 - https://www.dhinovatech.com\n\n特性：\n- 兼容 Windows 10 记事本\n- AES-256 加密文档 (.dhin)\n- 高级安全 UI");
        AddLang("tl", "File", "Bago", "Bagong Window", "Buksan...", "I-save", "I-save Bilang...", "Lumabas", "I-edit", "I-undo", "I-redo", "Gupitin", "Kopyahin", "I-paste", "Burahin", "Hanapin...", "Hanapin ang Susunod", "Hanapin ang Nakaraang", "Palitan...", "Pumunta sa...", "Piliin Lahat", "Oras/Petsa", "Format", "Word Wrap", "Tingnan", "Zoom", "Palakihin", "Paliitin", "Ibalik ang Default Zoom", "Status Bar", "Wika", "Awtomatiko (Wika ng Sistema)", "Tulong", "Tungkol sa Notelock", "Magsimulang mag-type...", "Walang Pamagat", "I-encrypt at I-save", "I-decrypt at Buksan", "I-encrypt ang Dokumento", "I-decrypt ang Dokumento", "Magtakda ng password.", "Ipasok ang password.", "Hindi pwedeng walang password", "Hindi magkatugma ang password", "Password", "Kumpirmahin ang Password", "Ipasok ang password", "Ulitin ang password", "Seguridad sa Pag-save ng Dokumento", "Piliin kung paano i-save ang dokumento:\n\n🔒 Na-encrypt na Dokumento (.dhin)\nProtektado ng password.\n\n📄 Plain Text na Dokumento (.txt)\nKaraniwang file.", "🔒 Na-encrypt (.dhin)", "📄 Plain Text (.txt)", "Gusto mo bang i-save ang mga pagbabago?", "Huwag I-save", "Hindi mahanap ang \"{0}\"", "Pinalitan ang lahat ng tugma.", "Numero ng linya", "Ang numero ng linya ay lumampas sa kabuuang linya.", "Bisitahin ang Website", "Bumagsak ang pag-decrypt. Mali ang password.", "Kanselahin", "OK", "Notelock Ligtas na Text Editor\nBersyon 3.0\n\nBinuo ng Dhinovatech - Bisitahin ang website - https://www.dhinovatech.com\n\nMga Tampok:\n- Windows 10 Notepad compatibility\n- AES-256 Na-encrypt na mga Dokumento (.dhin)\n- Premium Security UI");
        AddLang("ko", "파일", "새로 만들기", "새 창", "열기...", "저장", "다른 이름으로 저장...", "끝내기", "편집", "실행 취소", "다시 실행", "잘라내기", "복사", "붙여넣기", "삭제", "찾기...", "다음 찾기", "이전 찾기", "바꾸기...", "이동...", "모두 선택", "시간/날짜", "서식", "자동 줄 바꿈", "보기", "확대/축소", "확대", "축소", "기본 확대/축소 복원", "상태 표시줄", "언어", "자동 (시스템 언어)", "도움말", "Notelock 정보", "입력을 시작하세요...", "제목 없음", "암호화 및 저장", "복호화 및 열기", "문서 암호화", "문서 복호화", "비밀번호를 설정하세요.", "비밀번호를 입력하세요.", "비밀번호를 입력해야 합니다", "비밀번호가 일치하지 않습니다", "비밀번호", "비밀번호 확인", "비밀번호 입력", "비밀번호 재입력", "문서 저장 보안", "문서 저장 방식을 선택하세요:\n\n🔒 암호화 문서 (.dhin)\n비밀번호로 콘텐츠를 보호합니다.\n\n📄 일반 텍스트 문서 (.txt)\n기본 미암호화 파일.", "🔒 암호화 (.dhin)", "📄 일반 텍스트 (.txt)", "변경 사항을 저장하시겠습니까?", "저장 안 함", "\"{0}\"을(를) 찾을 수 없습니다.", "모든 항목이 바뀌었습니다.", "줄 번호", "줄 번호가 전체 줄 수를 초과했습니다.", "웹사이트 방문", "복호화 실패. 잘못된 비밀번호입니다.", "취소", "확인", "Notelock 보안 텍스트 편집기\n버전 3.0\n\nDhinovatech 개발 - 웹사이트 방문 - https://www.dhinovatech.com\n\n주요 기능:\n- Windows 10 메모장 호환\n- AES-256 암호화 문서 (.dhin)\n- 프리미엄 보안 UI");
        AddLang("fa", "فایل", "جدید", "پنجره جدید", "باز کردن...", "ذخیره", "ذخیره به عنوان...", "خروج", "ویرایش", "واگردانی", "انجام مجدد", "برش", "کپی", "چسباندن", "حذف", "یافتن...", "یافتن بعدی", "یافتن قبلی", "جایگزینی...", "رفت به خط...", "انتخاب همه", "زمان/تاریخ", "قالب‌بندی", "شکستن سطر", "نما", "زوم", "بزرگ‌نمایی", "کوچک‌نمایی", "بازنشانی زوم پیش‌فرض", "نوار وضعیت", "زبان", "خودکار (زبان سیستم)", "راهنما", "درباره Notelock", "شروع به تایپ کنید...", "بدون عنوان", "رمزگذاری و ذخیره", "رمزگشایی و باز کردن", "رمزگذاری سند", "رمزگشایی سند", "رمز عبور برای فایل تنظیم کنید.", "رمز عبور را وارد کنید.", "رمز عبور نمی‌تواند خالی باشد", "رمزهای عبور مطابقت ندارند", "رمز عبور", "تایید رمز عبور", "رمز عبور را وارد کنید", "تکرار رمز عبور", "امنیت ذخیره سند", "نحوه ذخیره سند خود را انتخاب کنید:\n\n🔒 سند رمزگذاری شده (.dhin)\nحفاظت از محتوا با رمز عبور.\n\n📄 سند متن ساده (.txt)\nفایل متنی معمولی.", "🔒 رمزگذاری شده (.dhin)", "📄 متن ساده (.txt)", "آیا می‌خواهید تغییرات این سند ذخیره شود؟", "ذخیره نشود", "\"{0}\" یافت نشد", "تمام موارد جایگزین شدند.", "شماره خط", "شماره خط بیشتر از کل خطوط است.", "بازدید از وب‌سایت", "رمزگشایی ناموفق بود. رمز عبور اشتباه است.", "لغو", "تایید", "ویرایشگر متن امن Notelock\nنسخه 3.0\n\nتوسعه یافته توسط Dhinovatech - بازدید از وب‌سایت - https://www.dhinovatech.com\n\nویژگی‌ها:\n- سازگاری با نوت‌پد ویندوز 10\n- اسناد رمزگذاری شده AES-256 (.dhin)\n- رابط کاربری امنیتی ویژه");
        AddLang("ha", "Fayil", "Sabo", "Sabon Window", "Bude...", "Ajiye", "Ajiye Matsayin...", "Fita", "Gyara", "Soke", "Maimaita", "Yanka", "Kwafi", "Manna", "Goge", "Nema...", "Nemi Na Gaba", "Nemi Na Baya", "Canza...", "Jeka...", "Zaɓa Duka", "Lokaci/Kwanan Wata", "Tsari", "Nannade Kalma", "Duba", "Girma", "Girmara", "Rage Girma", "Mayar Da Default Zoom", "Status Bar", "Harshe", "Mota (Harshen System)", "Taimako", "Game da Notelock", "Fara rubutu...", "Mara Suna", "Encryp & Ajiye", "Decryp & Bude", "Encryp Takarda", "Decryp Takarda", "Sanya password don kare fayil.", "Shigar da password.", "Password ba zai kasance kowa ba", "Password ba su zo daya ba", "Password", "Tabbatar da Password", "Shigar da password", "Maimaita password", "Kare Ajiye Takarda", "Zabi yadda kake son ajiye takarda:\n\n🔒 Encrypted Takarda (.dhin)\nKare fayil da password.\n\n📄 Plain Text Takarda (.txt)\nNormal text fayil.", "🔒 Encrypted (.dhin)", "📄 Plain Text (.txt)", "Kuna son ajiye sauye-sauyen takardar?", "Kar a ajiye", "Ba a sami \"{0}\" ba", "An sake canza duk abubuwa.", "Lamba na layi", "Lamba na layi ya wuce jimillar layi.", "Ziyarci Shafi", "Decryption ya gaza. Password bai dace ba.", "Fasa", "Ya yi", "Notelock Secure Text Editor\nForm 3.0\n\nDhinovatech ya yi amfani - Ziyarci shafi - https://www.dhinovatech.com\n\nAyyuka:\n- Windows 10 Notepad wuri daya\n- AES-256 Encrypted Takardu (.dhin)\n- TSORTA UI");
        AddLang("jv", "Berkas", "Anyar", "Jendela Anyar", "Bukak...", "Simpen", "Simpen Minangka...", "Metu", "Besut", "Batalake", "Baleni", "Kethok", "Salin", "Tempel", "Hapus", "Goleki...", "Goleki Sabanjure", "Goleki Sadurunge", "Ganti...", "Menyang...", "Pilih Kabeh", "Waktu/Tanggal", "Format", "Bungkus Tembung", "Deleng", "Zoom", "Gedeake", "Cilikake", "Balikake Zoom Default", "Status Bar", "Basa", "Otomatis (Basa Sistem)", "Pitulung", "Babagan Notelock", "Mulai ngetik...", "Tanpa Judul", "Enkripsi & Simpen", "Dekripsi & Bukak", "Enkripsi Dokumen", "Dekripsi Dokumen", "Setel sandi kanggo nglindhungi berkas.", "Mlebu sandi.", "Sandi ora kena kosong", "Sandi ora cocok", "Sandi", "Konfirmasi Sandi", "Mlebu sandi", "Baleni sandi", "Keamanan Nyimpen Dokumen", "Pilih cara nyimpen dokumen:\n\n🔒 Dokumen Enkripsi (.dhin)\nNglindhungi berkas nganggo sandi.\n\n📄 Dokumen Teks Biasa (.txt)\nBerkas biasa.", "🔒 Enkripsi (.dhin)", "📄 Teks Biasa (.txt)", "Apa sampeyan pengin nyimpen owah-owahan?", "Aja Simpen", "Ora bisa nemokake \"{0}\"", "Kabeh wis diganti.", "Nomer baris", "Nomer baris ngluwihi total baris.", "Dharani Situs Web", "Dekripsi gagal. Sandi salah.", "Batal", "Ya", "Editor Teks Aman Notelock\nVersi 3.0\n\nDigawe dening Dhinovatech - Dharani situs web - https://www.dhinovatech.com\n\nFitur:\n- Kompatibilitas Windows 10 Notepad\n- Dokumen Enkripsi AES-256 (.dhin)\n- UI Keamanan dhuwur");
        AddLang("pa", "ਫਾਈਲ", "ਨਵਾਂ", "ਨਵੀਂ ਵਿੰਡੋ", "ਖੋਲ੍ਹੋ...", "ਸੰਭਾਲੋ", "ਇਸ ਤਰ੍ਹਾਂ ਸੰਭਾਲੋ...", "ਬਾਹਰ ਨਿਕਲੋ", "ਸੋਧੋ", "ਵਾਪਸ ਲਵੋ", "ਮੁੜ ਕਰੋ", "ਕੱਟੋ", "ਕਾਪੀ", "ਪੇਸਟ", "ਹਟਾਓ", "ਖੋਜੋ...", "ਅਗਲਾ ਖੋਜੋ", "ਪਿਛਲਾ ਖੋਜੋ", "ਬਦਲੋ...", "ਲਾਈਨ 'ਤੇ ਜਾਓ...", "ਸਭ ਚੁਣੋ", "ਸਮਾਂ/ਮਿਤੀ", "ਫਾਰਮੈਟ", "ਵਰਡ ਰੈਪ", "ਵੇਖੋ", "ਜ਼ੂਮ", "ਜ਼ੂਮ ਇਨ", "ਜ਼ੂਮ ਆਊਟ", "ਡਿਫਾਲਟ ਜ਼ੂਮ ਰੀਸੈਟ ਕਰੋ", "ਸਥਿਤੀ ਪੱਟੀ", "ਭਾਸ਼ਾ", "ਆਟੋ (ਸਿਸਟਮ ਭਾਸ਼ਾ)", "ਮਦਦ", "Notelock ਬਾਰੇ", "ਟਾਈਪ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ...", "ਬਿਨਾਂ ਸਿਰਲੇਖ", "ਐਨਕ੍ਰਿਪਟ ਅਤੇ ਸੰਭਾਲੋ", "ਡੀਕ੍ਰਿਪਟ ਅਤੇ ਖੋਲ੍ਹੋ", "ਦਸਤਾਵੇਜ਼ ਐਨਕ੍ਰਿਪਟ ਕਰੋ", "ਦਸਤਾਵੇਜ਼ ਡੀਕ੍ਰਿਪਟ ਕਰੋ", "ਫਾਈਲ ਦੀ ਸੁਰੱਖਿਆ ਲਈ ਪਾਸਵਰਡ ਸੈੱਟ ਕਰੋ।", "ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ।", "ਪਾਸਵਰਡ ਖਾਲੀ ਨਹੀਂ ਹੋ ਸਕਦਾ", "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ", "ਪਾਸਵਰਡ", "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ", "ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ", "ਪਾਸਵਰਡ ਦੁਬਾਰਾ ਦਰਜ ਕਰੋ", "ਦਸਤਾਵੇਜ਼ ਸੁਰੱਖਿਆ ਸੰਭਾਲੋ", "ਚੁਣੋ ਕਿ ਤੁਸੀਂ ਦਸਤਾਵੇਜ਼ ਕਿਵੇਂ ਸੰਭਾਲਣਾ ਚਾਹੁੰਦੇ ਹੋ:\n\n🔒 ਐਨਕ੍ਰਿਪਟਡ ਦਸਤਾਵੇਜ਼ (.dhin)\nਪਾਸਵਰਡ ਨਾਲ ਸੁਰੱਖਿਅਤ।\n\n📄 ਪਲੇਨ ਟੈਕਸਟ ਦਸਤਾਵੇਜ਼ (.txt)\nਸਧਾਰਨ ਫਾਈਲ।", "🔒 ਐਨਕ੍ਰਿਪਟਡ (.dhin)", "📄 ਪਲੇਨ ਟੈਕਸਟ (.txt)", "ਕੀ ਤੁਸੀਂ ਇਸ ਦਸਤਾਵੇਜ਼ ਦੀਆਂ ਤਬਦੀਲੀਆਂ ਸੰਭਾਲਣਾ ਚਾਹੁੰਦੇ ਹੋ?", "ਨਾ ਸੰਭਾਲੋ", "\"{0}\" ਨਹੀਂ ਮਿਲਿਆ", "ਸਾਰੇ ਬਦਲ ਦਿੱਤੇ ਗਏ।", "ਲਾਈਨ ਨੰਬਰ", "ਲਾਈਨ ਨੰਬਰ ਕੁੱਲ ਲਾਈਨਾਂ ਤੋਂ ਵੱਧ ਹੈ।", "ਵੇਬਸਾਈਟ 'ਤੇ ਜਾਓ", "ਡੀਕ੍ਰਿਪਸ਼ਨ ਅਸਫਲ। ਗਲਤ ਪਾਸਵਰਡ।", "ਰੱਦ ਕਰੋ", "ਠੀਕ ਹੈ", "Notelock ਸੁਰੱਖਿਅਤ ਟੈਕਸਟ ਐਡੀਟਰ\nਵਰਜਨ 3.0\n\nDhinovatech ਦੁਆਰਾ ਵਿਕਸਤ - ਵੈੱਬਸਾਈਟ 'ਤੇ ਜਾਓ - https://www.dhinovatech.com\n\nਵਿਸ਼ੇਸ਼ਤਾਵਾਂ:\n- ਵਿੰਡੋਜ਼ 10 ਨੋਟਪੈਡ ਅਨੁਕੂਲਤਾ\n- AES-256 ਐਨਕ੍ਰਿਪਟਡ ਦਸਤਾਵੇਜ਼ (.dhin)\n- ਪ੍ਰੀਮੀਅਮ ਸੁਰੱਖਿਆ UI");
        AddLang("sw", "Faili", "Mpya", "Dirisha Jipya", "Fungua...", "Hifadhi", "Hifadhi Kama...", "Toka", "Hariri", "Tengua", "Rejesha", "Kata", "Nakili", "Bandika", "Futa", "Tafuta...", "Tafuta Inayofuata", "Tafuta Inayotangulia", "Badilisha...", "Nenda kwa...", "Chagua Zote", "Muda/Tarehe", "Muundo", "Mstari wa Neno", "Tazama", "Kuza", "Kuza Ndani", "Kuza Nje", "Weka Upya Zoom", "Mwambaa wa Hali", "Lugha", "Otomatiki (Lugha ya Mfumo)", "Msaada", "Kuhusu Notelock", "Anza kuandika...", "Bila Anwani", "Ficha na Hifadhi", "Fungua na Soma", "Ficha Hati", "Fungua Hati", "Weka nenosiri kulinda faili.", "Ingiza nenosiri.", "Nenosiri haliwezi kuwa tupu", "Nenosiri hazifanani", "Nenosiri", "Thibitisha Nenosiri", "Ingiza nenosiri", "Rudia nenosiri", "Usalama wa Kuhifadhi Hati", "Chagua jinsi unavyotaka kuhifadhi hati:\n\n🔒 Hati Iliyosimbwa (.dhin)\nInalinda kwa nenosiri.\n\n📄 Hati ya Maandishi (.txt)\nFaili ya kawaida.", "🔒 Iliyosimbwa (.dhin)", "📄 Maandishi (.txt)", "Je, unataka kuhifadhi mabadiliko kwenye hati hii?", "Usihifadhi", "Haitawezekana kupata \"{0}\"", "Yote yamebadilishwa.", "Nambari ya mstari", "Nambari ya mstari imezidi jumla ya mistari.", "Zuru Tovuti", "Usimbuaji umeshindwa. Nenosiri si sahihi.", "Ghairi", "Sawa", "Mhariri wa Maandishi Salama Notelock\nToleo 3.0\n\nImetengenezwa na Dhinovatech - Zuru tovuti - https://www.dhinovatech.com\n\nVipengele:\n- Utangamano na Windows 10 Notepad\n- Hati zilizosimbwa kwa AES-256 (.dhin)\n- UI ya Usalama wa Hali ya Juu");
        AddLang("it", "File", "Nuovo", "Nuova finestra", "Apri...", "Salva", "Salva con nome...", "Esci", "Modifica", "Annulla", "Ripristina", "Taglia", "Copia", "Incolla", "Elimina", "Trova...", "Trova successivo", "Trova precedente", "Sostituisci...", "Vai a...", "Seleziona tutto", "Ora/Data", "Formato", "A capo automatico", "Visualizza", "Zoom", "Ingrandisci", "Riduci", "Ripristina zoom predefinito", "Barra di stato", "Lingua", "Automatico (Lingua di sistema)", "Guida", "Informazioni su Notelock", "Inizia a digitare...", "Senza titolo", "Crittografa e salva", "Decrittografa e apri", "Crittografa documento", "Decrittografa documento", "Imposta una password di protezione.", "Inserisci la password.", "La password non può essere vuota", "Le password non corrispondono", "Password", "Conferma password", "Inserisci password", "Ripeti password", "Sicurezza salvataggio documento", "Scegli come salvare il documento:\n\n🔒 Documento crittografato (.dhin)\nProtegge il contenuto con password.\n\n📄 Documento di testo semplice (.txt)\nFile di testo normale.", "🔒 Crittografato (.dhin)", "📄 Testo semplice (.txt)", "Salvare le modifiche a questo documento?", "Non salvare", "Impossibile trovare \"{0}\"", "Tutte le occorrenze sono state sostituite.", "Numero di riga", "Il numero di riga supera il totale delle righe.", "Visita il sito web", "Decrittittazione non réussita. Password non valida.", "Annulla", "OK", "Editor di testo sicuro Notelock\nVersione 3.0\n\nSviluppato da Dhinovatech - Visita il sito web - https://www.dhinovatech.com\n\nCaratteristiche:\n- Compatibilità con Blocco note di Windows 10\n- Documenti crittografati AES-256 (.dhin)\n- Interfaccia di sicurezza Premium");
        AddLang("yo", "Fayili", "Titun", "Window Titun", "Sii...", "Pamo", "Pamo Bi...", "Jade", "Atunse", "Mura pada", "Tun se", "Ge", "Da kọ", "Lẹ pọ", "Parẹ", "Wa...", "Wa Ti N bọ", "Wa Ti Sẹhin", "Rọpọ...", "Lọ Si...", "Yan Gbogbo", "Akoko/Ọjọ", "Format", "Word Wrap", "Wo", "Zoom", "Mu tobi", "Mu kere", "Restoring Zoom Normal", "Status Bar", "Ede", "Aifọwọyi (Ede System)", "Iranlọwọ", "Nipa Notelock", "Bẹrẹ kíkọ...", "Laisi Areyin", "Encryp ati Pamo", "Decryp ati Sii", "Encryp Document", "Decryp Document", "Fi password si ti faili rẹ.", "Tẹ password rẹ si.", "Password kò le jẹ ofifo", "Password kò ba ara wọn mu", "Password", "Gba Password Ga", "Tẹ password rẹ si", "Tún password tẹ", "Ààbò Pamo Àkọsílẹ̀", "Yan bi o ṣe fẹ fi àkọsílẹ̀ rẹ pamọ:\n\n🔒 Àkọsílẹ̀ Encrypted (.dhin)\nFi password da ààbò si.\n\n📄 Àkọsílẹ̀ Plain Text (.txt)\nFaili text ti ko ni aabo.", "🔒 Encrypted (.dhin)", "📄 Plain Text (.txt)", "Ṣé o fẹ́ fi àwọn àtúnṣe pamọ́ sí àkọsílẹ̀ yìí?", "Mase pamọ", "Kò le ri \"{0}\"", "Gbogbo rẹ ti yipada.", "Nọmba ila", "Nọmba ila kọja papọ ila.", "Ṣabẹwo si Webisiiti", "Decryption kuna. Password ti kò ba mu.", "Fagilee", "Ó dáa", "Notelock Alakoso Ọrọ Titun\nAtẹjade 3.0\n\nDhinovatech kọ ọ - Ṣabẹwo si webisiiti - https://www.dhinovatech.com\n\nAwọn ẹya ara ẹrọ:\n- Ibaramu Windows 10 Notepad\n- Àkọsílẹ̀ Encrypted AES-256 (.dhin)\n- UI Ààbò Giga");
        AddLang("gu", "ફાઇલ", "નવું", "નવી વિન્ડો", "ખોલો...", "સાચવો", "આ રીતે સાચવો...", "બહાર નીકળો", "ફેરફાર કરો", "પૂર્વવત્ કરો", "ફરીથી કરો", "કાપો", "નકલ કરો", "ચોંટાડો", "કાઢી નાખો", "શોધો...", "આગળ શોધો", "પાછળ શોધો", "બદલો...", "લાઇન પર જાઓ...", "બધું પસંદ કરો", "સમય/તારીખ", "ફોર્મેટ", "વર્ડ રેપ", "જુઓ", "ઝૂમ", "ઝૂમ ઇન", "ઝૂમ આઉટ", "ડિફોલ્ટ ઝૂમ રીસેટ કરો", "સ્થિતિ પટ્ટી", "ભાષા", "ઓટો (સિસ્ટમ ભાષા)", "મદદ", "Notelock વિશે", "ટાઇપ કરવાનું શરૂ કરો...", "શીર્ષક વગરનું", "એનક્રિપ્ટ અને સાચવો", "ડીક્રિપ્ટ અને ખોલો", "દસ્તાવેજ એનક્રિપ્ટ કરો", "દસ્તાવેજ ડીક્રિપ્ટ કરો", "પાસવર્ડ સેટ કરો.", "પાસવર્ડ દાખલ કરો.", "પાસવર્ડ ખાલી હોઈ શકે નહીં", "પાસવર્ડ મેળ ખાતા નથી", "પાસવર્ડ", "પાસવર્ડની ખાતરી કરો", "પાસવર્ડ દાખલ કરો", "પાસવર્ડ ફરીથી દાખલ કરો", "દસ્તાવેજ સુરક્ષા સાચવો", "તમારો દસ્તાવેજ કેવી રીતે સાચવવો તે પસંદ કરો:\n\n🔒 એનક્રિપ્ટેડ દસ્તાવેજ (.dhin)\nપાસવર્ડ સાથે સંગ્રહ સાચવે છે.\n\n📄 પ્લેન ટેક્સ્ટ દસ્તાવેજ (.txt)\nસામાન્ય ફાઇલ.", "🔒 એનક્રિપ્ટેડ (.dhin)", "📄 પ્લેન ટેક્સ્ટ (.txt)", "શું તમે આ દસ્તાવેજમાં ફેરફારો સાચવવા માંગો છો?", "સાચવશો નહીં", "\"{0}\" મળ્યું નથી", "બધા સ્થાન બદલાઈ ગયા.", "લાઇન નંબર", "લાઇન નંબર કુલ લાઇન કરતાં વધુ છે.", "વેબસાઇટની મુલાકાત લો", "ડીક્રિપ્શન નિષ્ફળ. અમાન્ય પાસવર્ડ.", "રદ કરો", "બરાબર", "Notelock સુરક્ષિત ટેક્સ્ટ એડિટર\nઆવૃત્તિ 3.0\n\nDhinovatech દ્વારા વિકસિત - વેબસાઇટની મુલાકાત લો - https://www.dhinovatech.com\n\nવિશેષતાઓ:\n- વિન્ડોઝ 10 નોટપેડ સુસંગતતા\n- AES-256 એનક્રિપ્ટેડ દસ્તાવેજો (.dhin)\n- પ્રીમિયમ સિક્યુરિટી UI");
        AddLang("th", "ไฟล์", "สร้างใหม่", "หน้าต่างใหม่", "เปิด...", "บันทึก", "บันทึกเป็น...", "ออก", "แก้ไข", "เลิกทำ", "ทำซ้ำ", "ตัด", "คัดลอก", "วาง", "ลบ", "ค้นหา...", "ค้นหาถัดไป", "ค้นหาก่อนหน้า", "แทนที่...", "ไปที่...", "เลือกทั้งหมด", "เวลา/วันที่", "รูปแบบ", "ตัดคำ", "มุมมอง", "ย่อ/ขยาย", "ขยาย", "ย่อ", "รีเซ็ตการขยาย", "แถบสถานะ", "ภาษา", "อัตโนมัติ (ภาษาของระบบ)", "ช่วยเหลือ", "เกี่ยวกับ Notelock", "เริ่มพิมพ์...", "ไม่มีชื่อ", "เข้ารหัสและบันทึก", "ถอดรหัสและเปิด", "เข้ารหัสเอกสาร", "ถอดรหัสเอกสาร", "ตั้งรหัสผ่านเพื่อปกป้องไฟล์", "ป้อนรหัสผ่านเพื่อปลดล็อก", "รหัสผ่านต้องไม่ว่างเปล่า", "รหัสผ่านไม่ตรงกัน", "รหัสผ่าน", "ยืนยันรหัสผ่าน", "ป้อนรหัสผ่าน", "ป้อนรหัสผ่านอีกครั้ง", "ความปลอดภัยในการบันทึกเอกสาร", "เลือกวิธีบันทึกเอกสารของคุณ:\n\n🔒 เอกสารเข้ารหัส (.dhin)\nป้องกันเนื้อหาด้วยรหัสผ่าน\n\n📄 เอกสารข้อความธรรมดา (.txt)\nไฟล์ข้อความทั่วไป", "🔒 เข้ารหัส (.dhin)", "📄 ข้อความธรรมดา (.txt)", "คุณต้องการบันทึกการเปลี่ยนแปลงในเอกสารนี้หรือไม่?", "ไม่บันทึก", "ไม่พบ \"{0}\"", "แทนที่คำทั้งหมดเรียบร้อยแล้ว", "หมายเลขบรรทัด", "หมายเลขบรรทัดเกินจำนวนบรรทัดทั้งหมด", "เยี่ยมชมเว็บไซต์", "ถอดรหัสไม่สำเร็จ รหัสผ่านไม่ถูกต้อง", "ยกเลิก", "ตกลง", "โปรแกรมแก้ไขข้อความปลอดภัย Notelock\nเวอร์ชัน 3.0\n\nพัฒนาโดย Dhinovatech - เยี่ยมชมเว็บไซต์ - https://www.dhinovatech.com\n\nคุณสมบัติ:\n- เข้ากันได้กับ Windows 10 Notepad\n- เอกสารเข้ารหัส AES-256 (.dhin)\n- UI ความปลอดภัยพรีเมียม");
        AddLang("am", "ፋይል", "አዲስ", "አዲስ መስኮት", "ክፈት...", "አስቀምጥ", "እንደ አስቀምጥ...", "ውጣ", "አርትዕ", "መልስ", "ደግም", "ቁረጥ", "ቅዳ", "ለጥፍ", "ሰርዝ", "ፈልግ...", "ቀጣይ ፈልግ", "ቀዳሚ ፈልግ", "ተካ...", "ወደ... ሂድ", "ሁሉንም ምረጥ", "ሰዓት/ቀን", "ፎርማት", "የቃል መጠቅለያ", "እይታ", "አጉላ", "አጉላ", "አነስ", "ነባሪ አጉላ ይመልሱ", "የሁኔታ አሞሌ", "ቋንቋ", "አውቶማቲክ (የስርዓት ቋንቋ)", "እርዳታ", "ስለ Notelock", "መፃፍ ይጀምሩ...", "ርዕስ የሌለው", "ኢንክሪፕት ያድርጉ እና ያስቀምጡ", "ዲክሪፕት ያድርጉ እና ይክፈቱ", "ሰነድ ኢንክሪፕት ያድርጉ", "ሰነድ ዲክሪፕት ያድርጉ", "የይለፍ ቃል ያስቀምጡ።", "የይለፍ ቃል ያስገቡ።", "የይለፍ ቃል ባዶ መሆን አይችልም", "የይለፍ ቃሎች አይዛመዱም", "የይለፍ ቃል", "የይለፍ ቃል ያረጋግጡ", "የይለፍ ቃል ያስገቡ", "የይለፍ ቃል ይድገሙ", "የሰነድ ደህንነት ማስቀመጫ", "ሰነድዎን እንዴት ማስቀመጥ እንደሚፈልጉ ይምረጡ:\n\n🔒 ኢንክሪፕት የተደረገ ሰነድ (.dhin)\nበይለፍ ቃል ይጠበቃል።\n\n📄 የጽሑፍ ሰነድ (.txt)\nመደበኛ ፋይል।", "🔒 ኢንክሪፕት የተደረገ (.dhin)", "📄 የጽሑፍ ሰነድ (.txt)", "የዚህን ሰነድ ለውጦች ማስቀመጥ ይፈልጋሉ?", "አታስቀምጥ", "\"{0}\" ማግኘት አልተቻለም", "ሁሉም ተተክተዋል።", "የመስመር ቁጥር", "የመስመር ቁጥሩ ከአጠቃላይ መስመሮች በላይ ነው።", "ድር ጣቢያ ይጎብኙ", "ዲክሪፕት ማድረግ አልተሳካም። የተሳሳተ የይለፍ ቃል፤", "ሰርዝ", "እሺ", "Notelock ደህንነቱ የተጠበቀ የጽሑፍ አዘጋጅ\nስሪት 3.0\n\nበ Dhinovatech የበለፀገ - ድር ጣቢያ ይጎብኙ - https://www.dhinovatech.com\n\nባህሪያት:\n- ከ Windows 10 Notepad ጋር ተኳሃኝ\n- AES-256 ኢንክሪፕት የተደረጉ ሰነዶች (.dhin)\n- ከፍተኛ የደህንነት UI");
        AddLang("bho", "फाइल", "नया", "नया विंडो", "खोलीं...", "सहेजीं", "अइसन सहेजीं...", "बाहर निकरीं", "संपादन", "पछिली क्रिया", "फिर से करीं", "काटीं", "कॉपी करीं", "पेस्ट करीं", "हटाईं", "खोजीं...", "अगिला खोजीं", "पिछिला खोजीं", "बदलीं...", "लाइन पर जाईं...", "सभ चुनीं", "समय/तारीख", "प्रारूप", "शब्द लपेटीं", "देखीं", "ज़ूम", "ज़ूम इन", "ज़ूम आउट", "डिफ़ॉल्ट ज़ूम रीसेट करीं", "स्थिति पट्टी", "भाषा", "ऑटो (सिस्टम भाषा)", "मदद", "Notelock के बारे में", "टाइप कइल शुरू करीं...", "बिना शीर्षक", "एन्क्रिप्ट अउरी सहेजीं", "डीक्रिप्ट अउरी खोलीं", "दस्तावेज़ एन्क्रिप्ट करीं", "दस्तावेज़ डीक्रिप्ट करीं", "पासवर्ड सेट करीं।", "पासवर्ड डालीं।", "पासवर्ड खाली ना हो सकेला", "पासवर्ड मेल ना खात बा", "पासवर्ड", "पासवर्ड पक्का करीं", "पासवर्ड डालीं", "पासवर्ड फिर से डालीं", "दस्तावेज़ सुरक्षा सहेजीं", "चुनल जाईं कि दस्तावेज़ कइसे सहेजे के बा:\n\n🔒 एन्क्रिप्टेड दस्तावेज़ (.dhin)\nपासवर्ड से सामग्री सहेजेला।\n\n📄 प्लेन टेक्स्ट दस्तावेज़ (.txt)\nसामान्य फ़ाइल।", "🔒 एन्क्रिप्टेड (.dhin)", "📄 प्लेन टेक्स्ट (.txt)", "का राउर बदलाव सहेजल चाहत बानी?", "ना सहेजीं", "\"{0}\" ना मिलल", "सभ जगह बदला गइल।", "लाइन नंबर", "लाइन नंबर कुल लाइन से बेसी बा।", "वेबसाइट देखीं", "डीक्रिप्शन असफल। गलत पासवर्ड।", "रद्द करीं", "ठीक बा", "Notelock सुरक्षित पाठ संपादक\nसंस्करण 3.0\n\nDhinovatech द्वारा विकसित - वेबसाइट देखीं - https://www.dhinovatech.com\n\nविशेषता:\n- विंडोज 10 नोटपैड संगतता\n- AES-256 एन्क्रिप्टेड दस्तावेज़ (.dhin)\n- प्रीमियम सुरक्षा UI");
        AddLang("pl", "Plik", "Nowy", "Nowe okno", "Otwórz...", "Zapisz", "Zapisz jako...", "Wyjście", "Edycja", "Cofnij", "Ponów", "Wytnij", "Kopiuj", "Wklej", "Usuń", "Znajdź...", "Znajdź następny", "Znajdź poprzedni", "Zamień...", "Przejdź do...", "Zaznacz wszystko", "Godzina/Data", "Format", "Zawijanie wierszy", "Widok", "Powiększenie", "Powiększ", "Pomniejsz", "Przywróć domyślne powiększenie", "Pasek stanu", "Język", "Automatyczny (Język systemu)", "Pomoc", "O программе Notelock", "Zacznij pisać...", "Bez tytułu", "Szyfruj i zapisz", "Odszyfruj i otwórz", "Szyfruj dokument", "Odszyfruj dokument", "Ustaw hasło ochrony.", "Wprowadź hasło.", "Hasło nie może być puste", "Hasła nie są identyczne", "Hasło", "Potwierdź hasło", "Wprowadź hasło", "Powtórz hasło", "Bezpieczeństwo zapisu dokumentu", "Wybierz sposób zapisu dokumentu:\n\n🔒 Szyfrowany dokument (.dhin)\nChroniony hasłem.\n\n📄 Zwykły dokument tekstowy (.txt)\nStandardowy plik.", "🔒 Szyfrowany (.dhin)", "📄 Zwykły tekst (.txt)", "Czy chcesz zapisać zmiany w tym dokumencie?", "Nie zapisuj", "Nie można znaleźć \"{0}\"", "Wszystkie wystąpienia zostały zastąpione.", "Numer wiersza", "Numer wiersza przekracza łączną liczbę wierszy.", "Odwiedź stronę internetową", "Odszyfrowywanie nie powiodło się. Błędne hasło.", "Anuluj", "OK", "Bezpieczny edytor tekstu Notelock\nWersja 3.0\n\nStworzony przez Dhinovatech - Odwiedź stronę - https://www.dhinovatech.com\n\nFunkcje:\n- Zgodność z Notesem Windows 10\n- Szyfrowane dokumenty AES-256 (.dhin)\n- Zaawansowane UI bezpieczeństwa");
        AddLang("ps", "فایل", "نوی", "نوې کړکۍ", "خلاصول...", "خوندي کول", "په بله بڼه خوندي کول...", "وتل", "سمول", "بیرته راګرځول", "بیا کول", "پرې کول", "کاپي", "پیسټ", "حذف کول", "لټول...", "بل لټول", "مخکینی لټول", "بدلول...", "کرښې ته تلل...", "ټول ټاکل", "وخت/نېټه", "بڼه", "د کلمو پوښل", "لیدل", "زوم", "غټول", "وړوکی کول", "د پخواني زوم بحالول", "د حالت پټه", "ژبه", "اتوماتیک (د سیسټم ژبه)", "مرسته", "د Notelock په اړه", "لیکل پیل کړئ...", "بې سرلیکه", "انکرپټ او خوندي کول", "ډیکرپټ او خلاصول", "سند انکرپټ کول", "سند ډیکرپټ کول", "پټنوم وټاکئ.", "پټنوم دننه کړئ.", "پټنوم تش نشي پاتې کېدلی", "پټنومونه سم نه دي", "پټنوم", "د پټنوم تایید", "پټنوم دننه کړئ", "پټنوم بیا دننه کړئ", "د سند خوندي کولو امنیت", "د سند خوندي کولو لاره وټاکئ:\n\n🔒 انکرپټ شوی سند (.dhin)\nپه پټنوم خوندي شوی.\n\n📄 ساده متن سند (.txt)\nساده فایل.", "🔒 انکرپټ شوی (.dhin)", "📄 ساده متن (.txt)", "ایا غواړئ پدې سند کې بدلونونه خوندي کړئ؟", "مه خوندي کوئ", "\"{0}\" ونه موندل شو", "ټول د پخوا په څېر بدل شول.", "د کرښې شمیره", "د کرښې شمیره د ټولې کرښې د شمیر څخه زیاته ده.", "ویب پاڼه وګورئ", "ډیکرپشن ناکام شو. پټنوم غلط دی.", "لغوه کول", "سیمه ده", "د Notelock خوندي متن ایډیټر\nنسخه 3.0\n\nد Dhinovatech لخوا رامینځته شوی - ویب پاڼه وګورئ - https://www.dhinovatech.com\n\nبرخې:\n- د Windows 10 Notepad مطابقت\n- AES-256 انکرپټ شوي اسناد (.dhin)\n- پرمختللی امینتي UI");
        AddLang("or", "ଫାଇଲ୍", "ନୂଆ", "ନୂଆ ୱିଣ୍ଡୋ", "ଖୋଲନ୍ତୁ...", "ସଂରକ୍ଷଣ କରନ୍ତୁ", "ଏହିପରି ସଂରକ୍ଷଣ କରନ୍ତୁ...", "ପ୍ରସ୍ଥାନ", "ସମ୍ପାଦନା", "ପୂର୍ବବତ୍ କରନ୍ତୁ", "ପୁନର୍ବାର କରନ୍ତୁ", "କାଟନ୍ତୁ", "କପି", "ପେଷ୍ଟ", "ହଟାନ୍ତୁ", "ଖୋଜନ୍ତୁ...", "ପରବର୍ତ୍ତୀ ଖୋଜନ୍ତୁ", "ପୂର୍ବବର୍ତ୍ତୀ ଖୋଜନ୍ତୁ", "ବଦଳାନ୍ତୁ...", "ଧାଡ଼ିକୁ ଯାଆନ୍ତୁ...", "ସମସ୍ତ ଚୟନ କରନ୍ତୁ", "ସମୟ/ତାରିଖ", "ଫର୍ମାଟ୍", "ୱାର୍ଡ ରାପ୍", "ଦେଖନ୍ତୁ", "ଜୁମ୍", "ବଡ଼ କରନ୍ତୁ", "ସାନ କରନ୍ତୁ", "ଡିଫଲ୍ଟ ଜୁମ୍ ରିସେଟ୍ କରନ୍ତୁ", "ସ୍ଥିତି ପଟି", "ଭାଷା", "ଅଟୋ (ସିଷ୍ଟମ୍ ଭାଷା)", "ସହାୟତା", "Notelock ବିଷୟରେ", "ଟାଇପ୍ କରିବା ଆରମ୍ଭ କରନ୍ତୁ...", "ଶୀର୍ଷକହୀନ", "ଏନକ୍ରିପ୍ଟ & ସଂରକ୍ଷଣ", "ଡିକ୍ରିପ୍ଟ & ଖୋଲନ୍ତୁ", "ଡକ୍ୟୁମେଣ୍ଟ ଏନକ୍ରିପ୍ଟ କରନ୍ତୁ", "ଡକ୍ୟୁମେଣ୍ଟ ଡିକ୍ରିପ୍ଟ କରନ୍ତୁ", "ପାସୱାର୍ଡ ସେଟ୍ କରନ୍ତୁ।", "ପାସୱାର୍ଡ ଦିଅନ୍ତୁ।", "ପାସୱାର୍ଡ ଖାଲି ରହିପାରିବ ନାହିଁ", "ପାସୱାର୍ଡ ମେଳ ଖାଉନାହିଁ", "ପାସୱାର୍ଡ", "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ", "ପାସୱାର୍ଡ ଦିଅନ୍ତୁ", "ପାସୱାର୍ଡ ପୁନର୍ବାର ଦିଅନ୍ତୁ", "ଡକ୍ୟୁମେଣ୍ଟ ସୁରକ୍ଷା ସଂରକ୍ଷଣ", "ଆପଣଙ୍କ ଡକ୍ୟୁମେଣ୍ଟ ସଂରକ୍ଷଣ ପ୍ରକାର ବାଛନ୍ତୁ:\n\n🔒 ଏନକ୍ରିପ୍ଟେଡ୍ ଡକ୍ୟୁମେଣ୍ଟ (.dhin)\nପାସୱାର୍ଡ ସହିତ ସୁରକ୍ଷିତ।\n\n📄 ସାଧାରଣ ଟେକ୍ସଟ୍ ଡକ୍ୟୁମେଣ୍ଟ (.txt)\nସାଧାରଣ ଫାଇଲ୍।", "🔒 ଏନକ୍ରିପ୍ଟେଡ୍ (.dhin)", "📄 ସାଧାରଣ ଟେକ୍ସଟ୍ (.txt)", "ଆପଣ ଏହି ଡକ୍ୟୁମେଣ୍ଟରେ ପରିବର୍ତ୍ତନଗୁଡ଼ିକ ସଂରକ୍ଷଣ କରିବାକୁ ଚାହାଁନ୍ତି କି?", "ସଂରକ୍ଷଣ କରନ୍ତୁ ନାହିଁ", "\"{0}\" ମିଳିଲା ନାହିଁ", "ସମସ୍ତ ସ୍ଥାନ ବଦଳାଗଲା।", "ଧାଡ଼ି ସଂଖ୍ୟା", "ଧାଡ଼ି ସଂଖ୍ୟା ମୋଟ ଧାଡ଼ି ସଂଖ୍ୟାରୁ ଅଧିକ।", "ୱେବସାଇଟ୍ ପରିଦର୍ଶନ କରନ୍ତୁ", "ଡିକ୍ରିପସନ୍ ବିଫଳ। ଭୁଲ୍ ପାସୱାର୍ଡ।", "ବାତିଲ୍", "ଠିକ୍ ଅଛି", "Notelock ସୁରକ୍ଷିତ ଟେକ୍ସଟ୍ ଏଡିଟର୍\nସଂସ୍କରଣ 3.0\n\nDhinovatech ଦ୍ୱାରା ବିକଶିତ - ୱେବସାଇଟ୍ ଦେଖନ୍ତୁ - https://www.dhinovatech.com\n\nବୈଶିଷ୍ଟ୍ୟ:\n- Windows 10 ਨੋਟਪ୍ୟାଡ୍ ସହିତ ସୁସଙ୍ଗତ\n- AES-256 ଏନକ୍ରିପ୍ଟେଡ୍ ଡକ୍ୟୁମେଣ୍ଟ (.dhin)\n- ପ୍ରିମିୟମ୍ ସୁରକ୍ଷା UI");
        AddLang("nan", "檔案", "新建", "新視窗", "開啟...", "儲存", "另存為...", "退出", "編輯", "復原", "重做", "剪下", "複製", "貼上", "刪除", "尋找...", "尋找下一個", "尋找上一個", "替換...", "跳轉到...", "全選", "時間/日期", "格式", "自動換行", "檢視", "縮放", "放大", "縮小", "還原預設縮放", "狀態列", "語言", "自動（系統語言）", "說明", "關於 Notelock", "開始輸入...", "未命名", "加密並儲存", "解密並開啟", "加密文件", "解密文件", "設定密碼保護檔案。", "輸入密碼解鎖。", "密碼不能留空", "密碼唔相符", "密碼", "確認密碼", "輸入密碼", "再一次輸入密碼", "儲存文件安全設定", "選擇您要如何儲存文件：\n\n🔒 加密文件 (.dhin)\n以密碼保護內容。\n\n📄 純文字文件 (.txt)\n一般文字檔案。", "🔒 加密 (.dhin)", "📄 純文字 (.txt)", "敢要儲存對此文件的變更？", "免儲存", "搵無 \"{0}\"", "全部已經替換。", "行號", "行號超出總行數。", "造訪網站", "解密失敗。密碼無效。", "取消", "確定", "Notelock 安全文字編輯器\n版本 3.0\n\n由 Dhinovatech 開發 - 造訪網站 - https://www.dhinovatech.com\n\n功能：\n- 兼容 Windows 10 記事本\n- AES-256 加密文件 (.dhin)\n- 高級安全 UI");
        AddLang("ml", "ഫയൽ", "പുതിയത്", "പുതിയ വിൻഡോ", "തുറക്കുക...", "സംരക്ഷിക്കുക", "ഇതായി സംരക്ഷിക്കുക...", "പുറത്തുകടക്കുക", "തിരുത്തുക", "പഴയപടിയാക്കുക", "വീണ്ടും ചെയ്യുക", "കട്ട് ചെയ്യുക", "കോപ്പി ചെയ്യുക", "പേസ്റ്റ് ചെയ്യുക", "ഇല്ലാതാക്കുക", "കണ്ടെത്തുക...", "അടുത്തത് കണ്ടെത്തുക", "മുൻപത്തേത് കണ്ടെത്തുക", "മാറ്റുക...", "വരിയിലേക്ക് പോവുക...", "എല്ലാം തിരഞ്ഞെടുക്കുക", "സമയം/തീയതി", "ഫോർമാറ്റ്", "വേഡ് റാപ്പ്", "കാണുക", "സൂം", "വലുതാക്കുക", "ചെറുതാക്കുക", "ഡിഫോൾട്ട് സൂം പുനഃസ്ഥാപിക്കുക", "സ്റ്റാറ്റസ് ബാർ", "ഭാഷ", "ഓട്ടോ (സിസ്റ്റം ഭാഷ)", "സഹായം", "Notelock-നെ കുറിച്ച്", "തൈപ്പ് ചെയ്യാൻ തുടങ്ങുക...", "തലക്കെട്ടില്ലാത്തത്", "എൻക്രിപ്റ്റ് ചെയ്തു സംരക്ഷിക്കുക", "ഡിക്രിപ്റ്റ് ചെയ്തു തുറക്കുക", "രേഖ എൻക്രിപ്റ്റ് ചെയ്യുക", "രേഖ ഡിക്രിപ്റ്റ് ചെയ്യുക", "പാസ്‌വേഡ് നൽകുക.", "പാസ്‌വേഡ് നൽകുക.", "പാസ്‌വേഡ് ശൂന്യമാകരുത്", "പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല", "പാസ്‌വേഡ്", "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക", "പാസ്‌വേഡ് നൽകുക", "പാസ്‌വേഡ് വീണ്ടും നൽകുക", "രേഖ സംരക്ഷണ സുരക്ഷ", "നിങ്ങളുടെ രേഖ എങ്ങനെ സംരക്ഷിക്കണമെന്ന് തിരഞ്ഞെടുക്കുക:\n\n🔒 എൻക്രിപ്റ്റ് ചെയ്ത രേഖ (.dhin)\nപാസ്‌വേഡ് വഴി സംരക്ഷിച്ചിരിക്കുന്നു.\n\n📄 സാധാരണ ടെക്സ്റ്റ് രേഖ (.txt)\nസാധാരണ ഫയൽ.", "🔒 എൻക്രിപ്റ്റ് ചെയ്തത് (.dhin)", "📄 സാധാരണ ടെക്സ്റ്റ് (.txt)", "ഈ രേഖയിലെ മാറ്റങ്ങൾ സംരക്ഷിക്കണോ?", "സംരക്ഷിക്കേണ്ടതില്ല", "\"{0}\" കണ്ടെത്താനായില്ല", "എല്ലാ മാറ്റങ്ങളും വരുത്തി.", "വരി നമ്പർ", "വരി നമ്പർ ആകെ വരികളെക്കാൾ കൂടുതലാണ്.", "വെബ്സൈറ്റ് സന്ദർശിക്കുക", "ഡിക്രിപ്ഷൻ പരാജയപ്പെട്ടു. തെറ്റായ പാസ്‌വേഡ്.", "റദ്ദാക്കുക", "ശരി", "Notelock സുരക്ഷിത ടെക്സ്റ്റ് എഡിറ്റർ\nപതിപ്പ് 3.0\n\nDhinovatech വികസിപ്പിച്ചത് - വെബ്സൈറ്റ് സന്ദർശിക്കുക - https://www.dhinovatech.com\n\nസവിശേഷതകൾ:\n- വിൻഡോസ് 10 നോട്ട്പാഡ് അനുയോജ്യത\n- AES-256 എൻക്രിപ്റ്റ് ചെയ്ത രേഖകൾ (.dhin)\n- പ്രീമિયം സുരക്ഷാ UI");
        AddLang("nl", "Bestand", "Nieuw", "Nieuw venster", "Openen...", "Opslaan", "Opslaan als...", "Afsluiten", "Bewerken", "Ongedaan maken", "Opnieuw", "Knippen", "Kopiëren", "Plakken", "Verwijderen", "Zoeken...", "Volgende zoeken", "Vorige zoeken", "Vervangen...", "Ga naar...", "Alles selecteren", "Tijd/Datum", "Opmaak", "Automatische terugloop", "Beeld", "Zoom", "Inzoomen", "Uitzoomen", "Standaardzoom herstellen", "Statusbalk", "Taal", "Auto (Systeemtaal)", "Help", "Over Notelock", "Begin met typen...", "Naamloos", "Versleutelen & Opslaan", "Ontsleutelen & Openen", "Document versleutelen", "Document ontsleutelen", "Stel een wachtwoord in.", "Voer het wachtwoord in.", "Wachtwoord mag niet leeg zijn", "Wachtwoorden komen niet overeen", "Wachtwoord", "Bevestig wachtwoord", "Voer wachtwoord in", "Herhaal wachtwoord", "Beveiliging bij opslaan document", "Kies hoe u uw document wilt opslaan:\n\n🔒 Versleuteld document (.dhin)\nBeschermt inhoud met een wachtwoord.\n\n📄 Plat tekst-document (.txt)\nStandaard onversleuteld bestand.", "🔒 Versleuteld (.dhin)", "📄 Plat tekst (.txt)", "Wilt u de wijzigingen in dit document opslaan?", "Niet opslaan", "Kan \"{0}\" niet vinden", "Alle voorkomsten zijn vervangen.", "Regelnummer", "Het regelnummer overschrijdt het totale aantal regels.", "Website bezoeken", "Ontsleuteling mislukt. Ongeldig wachtwoord.", "Annuleren", "OK", "Veilige teksteditor Notelock\nVersie 3.0\n\nOntwikkeld door Dhinovatech - Website bezoeken - https://www.dhinovatech.com\n\nFuncties:\n- Windows 10 Kladblok-compatibiliteit\n- AES-256 versleutelde documenten (.dhin)\n- Premium beveiligings-UI");

        return map;
    }
}
